// 수업 콘텐츠 데이터: 챕터·글자 카드·교사 노트·도입 슬라이드 자료
export type Character = {
  glyph: string;
  reading: string;
  strokes: number;
  story: string;
  related: string[];
  image?: string;
  source?: string;
  variant?: string;
  variantName?: string;
  kind?: string;
  ancientNote?: string;
  ancientLabel?: string;
};

export type Chapter = {
  no: string;
  nav: string;
  title: string;
  focus: string;
  count: string;
  objective: string;
  range: string;
  cue: string;
  activity: string;
  characters: Character[];
  intro?: boolean;
  appendix?: boolean;
};

export const chapters: Chapter[] = [
  {
    no: '00', nav: '수업 들어가기', title: '부수와 필순의 지도', focus: '위치 · 명칭 · 필순 · 자형 변화', count: '0', intro: true,
    objective: '부수가 글자 안에서 놓이는 위치의 이름을 알고, 기본 필순과 갑골문에서 해서까지의 자형 변화를 한눈에 이해합니다.',
    range: '변 · 방 · 머리 · 발 · 엄 · 몸 · 받침 · 제부수 / 기본 필순 8원칙 / 갑골문 → 금문 → 소전 → 예서 → 해서',
    cue: '“같은 부수도 자리가 달라지면 왜 모양과 이름이 달라질까요?”',
    activity: '글자의 부수 위치를 말하고, 다음 획을 손가락으로 예측한 뒤 자형 변화에서 남은 특징을 찾아봅니다.',
    characters: [
      { glyph: '部', reading: '떼 부', strokes: 11, kind: '기초 개념', story: '부수 수업에 들어가기 전에 위치 이름, 필순, 자형 변화의 큰 지도를 먼저 확인합니다.', related: ['部首 부수', '位置 위치', '筆順 필순'] },
    ],
  },
  {
    no: '01', nav: '부수의 원리', title: '그림이 글자가 되는 순간', focus: '상형 · 부수 · 의미의 뿌리', count: '18',
    objective: '가장 단순한 1·2획 부수부터 살펴보며, 부수가 뜻을 직접 나타내기도 하고 글자의 모양을 분류하는 표지가 되기도 함을 이해합니다.',
    range: '一 丨 丶 丿 乙 亅 二 亠 人 儿 入 八 冂 冖 冫 几 凵 刀',
    cue: '“이 부수는 뜻의 단서일까요, 모양을 분류하는 표지일까요?”',
    activity: '18자를 획의 방향·열린 방향·뜻의 유무에 따라 분류하고, 닮은 부수끼리 차이를 설명합니다.',
    characters: [
      { glyph: '一', reading: '한 일', strokes: 1, image: '/oracle/一.svg', source: 'https://commons.wikimedia.org/wiki/File:一-oracle.svg', kind: '지사', ancientNote: '갑골문에서도 가로 한 줄로 수 하나를 표시했습니다.', story: '가로선 하나로 수 1을 가리킨 지사자입니다. 위·아래를 나누는 기준선이나 하나로 이어진 상태도 나타냅니다.', related: ['三 석 삼', '上 위 상', '下 아래 하'] },
      { glyph: '丨', reading: '뚫을 곤', strokes: 1, image: '/oracle/丨.svg', source: 'https://commons.wikimedia.org/wiki/File:丨-bigseal.svg', ancientLabel: '대전(大篆)', kind: '형태 부수', ancientNote: '독립 갑골문은 확인되지 않아 후대의 대전 자형을 제시합니다.', story: '위에서 아래로 곧게 내려오는 세로획입니다. 관련 글자에서 언제나 ‘뚫다’라는 뜻을 주는 것은 아니므로 형태 분류용 부수임을 강조합니다.', related: ['中 가운데 중', '申 펼 신', '串 꿸 관'] },
      { glyph: '丶', reading: '점 주', strokes: 1, image: '/oracle/丶.svg', source: 'https://commons.wikimedia.org/wiki/File:丶-bronze.svg', ancientLabel: '금문(金文)', kind: '형태 부수', ancientNote: '독립 갑골문 대신 청동기에 남은 금문 자형을 제시합니다.', story: '짧게 찍는 점 한 획입니다. 글자 속 작은 표시를 모아 찾기 위한 부수이며, 실제 의미는 글자마다 다릅니다.', related: ['主 주인 주', '丹 붉을 단', '丸 둥글 환'] },
      { glyph: '丿', reading: '삐침 별', strokes: 1, image: '/oracle/丿.svg', source: 'https://commons.wikimedia.org/wiki/File:丿-bigseal.svg', ancientLabel: '대전(大篆)', kind: '형태 부수', ancientNote: '독립 갑골문은 확인되지 않아 대전에서 삐침 모양을 확인합니다.', story: '오른쪽 위에서 왼쪽 아래로 흘려 내리는 삐침 획입니다. 독립된 뜻보다는 자형을 분류하는 기준으로 사용됩니다.', related: ['乏 모자랄 핍', '乎 어조사 호', '乘 탈 승'] },
      { glyph: '乙', reading: '새 을', strokes: 1, image: '/oracle/乙.svg', source: 'https://commons.wikimedia.org/wiki/File:乙-oracle.svg', kind: '상형·가차', ancientNote: '굽고 꺾인 선으로 나타난 여러 갑골문 자형이 전합니다.', story: '굽어 자라는 싹이나 휘어진 모습을 본뜬 것으로 풀이하지만, 일찍부터 천간의 둘째 이름으로 빌려 썼습니다.', related: ['九 아홉 구', '乞 빌 걸', '乳 젖 유'] },
      { glyph: '亅', reading: '갈고리 궐', strokes: 1, image: '/oracle/亅.svg', source: 'https://commons.wikimedia.org/wiki/File:亅-seal.svg', ancientLabel: '소전(小篆)', kind: '형태 부수', ancientNote: '독립 갑골문·금문은 확인되지 않아 설문계 소전 자형을 제시합니다.', story: '세로획 끝을 위로 살짝 들어 올린 갈고리 모양입니다. 부수 이름과 실제 글자의 뜻이 직접 연결되지 않는 경우가 많습니다.', related: ['了 마칠 료', '事 일 사', '予 나 여'] },
      { glyph: '二', reading: '두 이', strokes: 2, image: '/oracle/二.svg', source: 'https://commons.wikimedia.org/wiki/File:二-oracle.svg', kind: '지사', ancientNote: '갑골문에서도 가로선을 두 번 그어 수 2를 표시했습니다.', story: '가로선 두 개로 둘을 가리킨 지사자입니다. 一에서 선을 하나 늘렸다는 생성 원리를 쉽게 비교할 수 있습니다.', related: ['三 석 삼', '五 다섯 오', '云 이를 운'] },
      { glyph: '亠', reading: '돼지해머리 두', strokes: 2, image: '/oracle/亠.svg', source: 'https://commons.wikimedia.org/wiki/File:亠-seal.svg', ancientLabel: '소전(小篆)', kind: '형태 부수', ancientNote: '독립 갑골문은 확인되지 않아 소전 자형을 제시합니다.', story: '점 아래에 가로선이 놓인 머리 모양의 부수입니다. 독립 글자로 외우기보다 亡·交·京의 공통 윗부분으로 찾습니다.', related: ['亡 망할 망', '交 사귈 교', '京 서울 경'] },
      { glyph: '人', reading: '사람 인', strokes: 2, image: '/oracle/人.svg', source: 'https://commons.wikimedia.org/wiki/File:人-oracle.svg', kind: '상형', variant: '亻', variantName: '亻 · 사람인변', ancientNote: '사람이 허리를 약간 굽히고 서 있는 옆모습을 그렸습니다.', story: '머리와 몸통을 한 획으로, 다리를 다른 한 획으로 나타낸 사람의 옆모습입니다. 왼쪽에서는 亻로 변합니다.', related: ['休 쉴 휴', '住 살 주', '信 믿을 신'] },
      { glyph: '儿', reading: '어진 사람 인', strokes: 2, image: '/oracle/儿.svg', source: 'https://commons.wikimedia.org/wiki/File:儿-oracle.svg', kind: '상형·변형', ancientNote: '사람의 두 다리를 중심으로 남긴 옛 자형입니다.', story: '사람의 아랫부분, 특히 두 다리가 벌어진 모습을 나타냅니다. 글자 아래에서 사람이 서 있는 모양을 찾게 합니다.', related: ['元 으뜸 원', '兄 형 형', '先 먼저 선'] },
      { glyph: '入', reading: '들 입', strokes: 2, image: '/oracle/入.svg', source: 'https://commons.wikimedia.org/wiki/File:入-oracle.svg', kind: '지사·상형', ancientNote: '두 선이 안쪽 한 지점으로 모이는 모습을 나타냈습니다.', story: '바깥에서 안으로 들어가듯 두 획이 서로 모입니다. 人은 아래가 벌어지고 入은 위가 맞닿는 차이를 비교합니다.', related: ['內 안 내', '全 온전 전', '兩 두 량'] },
      { glyph: '八', reading: '여덟 팔', strokes: 2, image: '/oracle/八.svg', source: 'https://commons.wikimedia.org/wiki/File:八-oracle.svg', kind: '지사·가차', ancientNote: '두 선이 좌우로 갈라지는 모습이 옛 자형에도 나타납니다.', story: '가운데에서 양쪽으로 나뉘는 모습으로 ‘나누다’의 뜻을 나타냈고, 수 8을 적는 글자로 빌려 쓰게 되었습니다.', related: ['分 나눌 분', '公 공평할 공', '共 함께 공'] },
      { glyph: '冂', reading: '멀 경', strokes: 2, image: '/oracle/冂.svg', source: 'https://commons.wikimedia.org/wiki/File:冂-bronze.svg', ancientLabel: '금문(金文)', kind: '상형·형태', ancientNote: '독립 갑골문 대신 금문에서 바깥 테두리의 옛 모양을 확인합니다.', story: '아래쪽이 열린 큰 테두리입니다. 冖·凵과 어느 방향이 열렸는지 비교하면 형태를 쉽게 구별할 수 있습니다.', related: ['同 한가지 동', '冊 책 책', '再 두 재'] },
      { glyph: '冖', reading: '덮을 멱', strokes: 2, image: '/oracle/冖.svg', source: 'https://commons.wikimedia.org/wiki/File:冖-oracle.svg', kind: '상형', ancientNote: '천이나 덮개가 위에서 내려와 가리는 모습을 그렸습니다.', story: '위에서 물건을 덮는 천이나 지붕을 나타냅니다. 宀보다 한 획 적고 가운데 점이 없다는 점을 관찰합니다.', related: ['冠 갓 관', '冥 어두울 명', '軍 군사 군'] },
      { glyph: '冫', reading: '얼음 빙', strokes: 2, image: '/oracle/冫.svg', source: 'https://commons.wikimedia.org/wiki/File:冫-oracle.svg', kind: '상형·변형', ancientNote: '얼음의 갈라진 결이나 얼음 조각을 점으로 표시한 형태입니다.', story: '물 水가 얼어붙은 상태를 두 점으로 간결하게 나타낸 부수입니다. 차가움·얼음과 관련된 글자를 묶습니다.', related: ['冬 겨울 동', '冷 찰 랭', '凍 얼 동'] },
      { glyph: '几', reading: '안석 궤', strokes: 2, image: '/oracle/几.svg', source: 'https://commons.wikimedia.org/wiki/File:几-bigseal.svg', ancientLabel: '대전(大篆)', kind: '상형', ancientNote: '독립 갑골문 대신 대전에서 낮은 안석의 옛 윤곽을 확인합니다.', story: '다리가 짧은 낮은 탁자 또는 팔걸이의 모습을 본뜬 글자입니다. 几와 凵의 끝부분 방향을 비교합니다.', related: ['凡 무릇 범', '凰 봉황새 황', '凱 개선할 개'] },
      { glyph: '凵', reading: '입 벌릴 감', strokes: 2, image: '/oracle/凵.svg', source: 'https://commons.wikimedia.org/wiki/File:凵-oracle.svg', kind: '상형·형태', ancientNote: '위쪽이 열린 그릇이나 움푹 팬 곳의 윤곽을 나타냈습니다.', story: '위가 열린 네모꼴입니다. 물건을 담거나 안에서 밖으로 나오는 장면을 가진 글자에서 찾을 수 있습니다.', related: ['凶 흉할 흉', '出 날 출', '函 함 함'] },
      { glyph: '刀', reading: '칼 도', strokes: 2, image: '/oracle/刀.svg', source: 'https://commons.wikimedia.org/wiki/File:刀-oracle.svg', kind: '상형', variant: '刂', variantName: '刂 · 선칼도방', ancientNote: '한쪽에 날이 선 칼의 옆모습이 옛 자형에 뚜렷합니다.', story: '손잡이와 굽은 칼날을 본뜬 글자입니다. 글자 오른쪽에서는 刂로 서서 자르기·나누기의 뜻을 암시합니다.', related: ['切 끊을 절', '分 나눌 분', '別 다를 별'] },
    ],
  },
  {
    no: '02', nav: '사람과 몸', title: '몸은 가장 가까운 사전', focus: '사람 · 감각 · 마음', count: '22',
    objective: '몸의 모양에서 시작한 부수를 알아보고, 인물의 상태와 감각·감정에 관한 뜻을 추론합니다.',
    range: '人 女 子 口 目 耳 手 足 心 首 面 毛 肉 身 骨 牙 舌 血 爪 臼 尸 鬼',
    cue: '“글자에서 몸의 어느 부분이 뜻을 맡고 있나요?”',
    activity: '休·信·好·聞·想을 사람/감각/마음 세 구역에 배치하고 이유를 말합니다.',
    characters: [
      { glyph: '人', reading: '사람 인', strokes: 2, image: '/oracle/人.svg', source: 'https://commons.wikimedia.org/wiki/File:人-oracle.svg', kind: '상형', variant: '亻', variantName: '亻 · 사람인변', ancientNote: '사람이 허리를 약간 굽히고 서 있는 옆모습입니다.', story: '사람의 몸통과 두 다리를 간결한 두 획으로 나타냈습니다. 왼쪽에 붙으면 亻가 되어 사람의 행동·관계를 암시합니다.', related: ['休 쉴 휴', '住 살 주', '信 믿을 신'] },
      { glyph: '女', reading: '계집 녀', strokes: 3, image: '/oracle/女.svg', source: 'https://commons.wikimedia.org/wiki/File:女-oracle.svg', kind: '상형', ancientNote: '무릎을 꿇고 두 손을 모은 사람의 모습을 그렸습니다.', story: '사람이 무릎을 모으고 앉은 모습을 본뜬 글자입니다. 역사적 자형의 설명과 오늘날의 성 역할은 구분해서 다룹니다.', related: ['好 좋을 호', '姓 성 성', '妹 누이 매'] },
      { glyph: '子', reading: '아들 자', strokes: 3, image: '/oracle/子.svg', source: 'https://commons.wikimedia.org/wiki/File:子-oracle.svg', kind: '상형', ancientNote: '머리가 크고 두 팔을 벌린 어린아이의 모습을 나타냈습니다.', story: '포대기에 싸이거나 두 팔을 벌린 어린아이를 정면에서 본 모습입니다. 아이·자식·배움의 뜻으로 확장됩니다.', related: ['字 글자 자', '孫 손자 손', '學 배울 학'] },
      { glyph: '口', reading: '입 구', strokes: 3, image: '/oracle/口.svg', source: 'https://commons.wikimedia.org/wiki/File:口-oracle.svg', kind: '상형', ancientNote: '벌린 입의 윤곽을 네모에 가까운 모양으로 표시했습니다.', story: '입의 윤곽을 단순하게 그렸습니다. 말하기·먹기·소리와 관련된 글자에서 뜻을 맡고, 囗과 크기를 비교합니다.', related: ['味 맛 미', '唱 부를 창', '問 물을 문'] },
      { glyph: '目', reading: '눈 목', strokes: 5, image: '/oracle/目.svg', source: 'https://commons.wikimedia.org/wiki/File:目-oracle.svg', kind: '상형', ancientNote: '가로로 놓인 눈과 눈동자를 그린 자형이 세로꼴로 정리되었습니다.', story: '눈의 윤곽과 눈동자를 세워 놓은 모양입니다. 보기·살피기·눈의 상태와 관련된 뜻을 만듭니다.', related: ['眼 눈 안', '看 볼 간', '眠 잘 면'] },
      { glyph: '耳', reading: '귀 이', strokes: 6, image: '/oracle/耳.svg', source: 'https://commons.wikimedia.org/wiki/File:耳-oracle.svg', kind: '상형', ancientNote: '귓바퀴의 굴곡을 옆에서 본 모습이 갑골문에 자세히 나타납니다.', story: '귓바퀴와 안쪽의 굴곡을 본뜬 글자입니다. 듣기·소리·귀의 상태와 관련된 한자를 분류합니다.', related: ['聞 들을 문', '聽 들을 청', '聲 소리 성'] },
      { glyph: '手', reading: '손 수', strokes: 4, image: '/oracle/手.svg', source: 'https://commons.wikimedia.org/wiki/File:手-bronze.svg', ancientLabel: '금문(金文)', kind: '상형', variant: '扌', variantName: '扌 · 재방변', ancientNote: '네이버 한자로드와 공개 도판에서 확인되는 금문 자형입니다. 독립된 手 갑골문 도판은 확인되지 않았습니다.', story: '손바닥과 손가락을 나타냈습니다. 왼쪽에 붙으면 扌가 되어 잡기·치기·들기 같은 손동작을 암시합니다.', related: ['打 칠 타', '持 가질 지', '拾 주울 습'] },
      { glyph: '足', reading: '발 족', strokes: 7, image: '/oracle/足.svg', source: 'https://commons.wikimedia.org/wiki/File:足-oracle.svg', kind: '상형', variant: '⻊', variantName: '⻊ · 발족변', ancientNote: '무릎 아래로 이어지는 종아리와 발의 모양을 나타냈습니다.', story: '다리 아래의 발을 본뜬 글자입니다. 왼쪽에서는 ⻊로 줄어 걷기·뛰기·길과 관련된 뜻을 만듭니다.', related: ['路 길 로', '跳 뛸 도', '踏 밟을 답'] },
      { glyph: '心', reading: '마음 심', strokes: 4, image: '/oracle/心.svg', source: 'https://commons.wikimedia.org/wiki/File:心-oracle.svg', kind: '상형', variant: '忄·⺗', variantName: '忄 · 심방변 / ⺗ · 마음심발', ancientNote: '심방과 심실처럼 갈라진 심장의 윤곽을 본뜬 자형입니다.', story: '심장의 윤곽에서 출발해 감정과 생각을 나타내게 된 글자입니다. 자리마다 心·忄·⺗로 모습이 달라집니다.', related: ['情 뜻 정', '想 생각 상', '忘 잊을 망'] },
      { glyph: '首', reading: '머리 수', strokes: 9, image: '/oracle/首.svg', source: 'https://commons.wikimedia.org/wiki/File:首-oracle.svg', kind: '상형', ancientNote: '머리카락과 눈이 강조된 사람의 머리를 갑골문에서 정면으로 그렸습니다.', story: '머리카락이 있는 머리의 모습을 본뜬 글자입니다. 신체의 맨 위라는 뜻에서 ‘첫째·우두머리’로도 확장됩니다.', related: ['首都 수도', '首位 수위', '道 길 도'] },
      { glyph: '面', reading: '낯 면', strokes: 9, image: '/oracle/面.svg', source: 'https://commons.wikimedia.org/wiki/File:面-oracle.svg', kind: '상형', ancientNote: '머리의 윤곽 안에 눈을 크게 넣어 얼굴 전체를 나타낸 갑골문입니다.', story: '사람의 얼굴 윤곽과 눈을 함께 그린 모습입니다. 얼굴에서 물체의 겉면·방향·마주함의 뜻으로 넓어졌습니다.', related: ['正面 정면', '表面 표면', '顔 얼굴 안'] },
      { glyph: '毛', reading: '터럭 모', strokes: 4, image: '/oracle/毛.svg', source: 'https://commons.wikimedia.org/wiki/File:毛-bronze.svg', ancientLabel: '금문(金文)', kind: '상형', ancientNote: '독립 갑골문 도판은 확인되지 않아 금문 자형을 제시합니다.', story: '피부 위에 난 털의 굽은 모양을 본뜬 글자입니다. 털·모직·매우 작은 양을 나타내는 말에 쓰입니다.', related: ['毛髮 모발', '羽毛 우모', '毯 담요 담'] },
      { glyph: '肉', reading: '고기 육', strokes: 6, image: '/oracle/肉.webp', source: 'https://commons.wikimedia.org/wiki/File:肉-oracle.svg', kind: '상형', variant: '月', variantName: '月 · 육달월', ancientNote: '살코기 덩어리 안쪽의 결을 두 줄로 표시한 갑골문입니다.', story: '잘라 놓은 고깃덩어리와 살의 결을 나타냈습니다. 글자 안에서는 月 모양으로 바뀌어 몸·장기·살의 뜻을 맡습니다.', related: ['胃 밥통 위', '肺 허파 폐', '腸 창자 장'] },
      { glyph: '身', reading: '몸 신', strokes: 7, image: '/oracle/身.png', source: 'https://commons.wikimedia.org/wiki/File:身-oracle.svg', kind: '상형', ancientNote: '배가 불룩한 사람의 옆모습으로 몸 전체를 나타낸 갑골문입니다.', story: '머리부터 몸통까지 사람의 몸 전체를 옆에서 본 모습입니다. 몸소·자기 자신이라는 뜻으로도 쓰입니다.', related: ['躬 몸 궁', '軀 몸 구', '射 쏠 사'] },
      { glyph: '骨', reading: '뼈 골', strokes: 10, image: '/oracle/骨.png', source: 'https://commons.wikimedia.org/wiki/File:冎-oracle.svg', kind: '상형·회의', ancientNote: '骨-oracle 파일은 옛 구성 요소 冎의 갑골 자형으로 연결됩니다. 아래의 肉과 결합해 骨이 되었습니다.', story: '뼈를 나타내는 冎와 살을 나타내는 肉이 결합한 것으로 풀이합니다. 뼈·골격·몸의 중심을 나타내는 글자에서 의미를 맡습니다.', related: ['體 몸 체', '骸 뼈 해', '髓 골수 수'] },
      { glyph: '牙', reading: '어금니 아', strokes: 4, image: '/oracle/牙.png', source: 'https://commons.wikimedia.org/wiki/File:牙-bronze.svg', ancientLabel: '금문(金文)', kind: '상형', ancientNote: '네이버 한자로드에서도 금문·소전·해서를 제시하며 독립 갑골문은 확인되지 않습니다.', story: '짐승이나 사람의 큰 어금니가 맞물린 모습을 본뜬 글자입니다. 이·송곳니와 관련된 뜻을 나타냅니다.', related: ['牙齒 아치', '象牙 상아', '芽 싹 아'] },
      { glyph: '舌', reading: '혀 설', strokes: 6, image: '/oracle/舌.png', source: 'https://commons.wikimedia.org/wiki/File:舌-oracle.svg', kind: '상형', ancientNote: '입에서 길게 나온 혀의 끝을 강조한 갑골문입니다.', story: '입 口 밖으로 혀가 나온 모습을 나타냈습니다. 혀·맛·말하기와 관련된 뜻을 떠올리게 합니다.', related: ['舐 핥을 지', '舌端 설단', '話 말씀 화'] },
      { glyph: '血', reading: '피 혈', strokes: 6, image: '/oracle/血.png', source: 'https://commons.wikimedia.org/wiki/File:血-oracle.svg', kind: '상형·회의', ancientNote: '그릇 안에 담긴 핏방울을 표시한 갑골문 제사 장면입니다.', story: '그릇 皿 안에 피가 담긴 모습을 나타낸 것으로 풀이합니다. 피·혈통·희생 제의의 뜻과 연결됩니다.', related: ['血管 혈관', '血族 혈족', '衆 무리 중'] },
      { glyph: '爪', reading: '손톱 조', strokes: 4, image: '/oracle/爪.png', source: 'https://commons.wikimedia.org/wiki/File:爪-oracle.svg', kind: '상형', variant: '爫', variantName: '爫 · 손톱조머리', ancientNote: '손가락을 아래로 뻗어 물건을 움켜잡는 손을 그린 갑골문입니다.', story: '위에서 아래로 뻗어 잡는 손과 손톱의 모습입니다. 글자 위에서는 爫로 변해 잡기·고르기의 뜻을 보탭니다.', related: ['采 캘 채', '受 받을 수', '爭 다툴 쟁'] },
      { glyph: '臼', reading: '절구 구', strokes: 6, image: '/oracle/臼.png', source: 'https://commons.wikimedia.org/wiki/File:Shuowen_Seal_Radical_134.svg', ancientLabel: '소전(小篆)', kind: '상형', ancientNote: '네이버 한자로드에서 금문·소전·해서가 확인됩니다. 공개 갑골문 도판은 확인되지 않아 설문 소전을 제시합니다.', story: '가운데가 움푹 파인 절구를 위에서 본 모습입니다. 이후 여러 글자의 양옆 구성 요소로도 쓰입니다.', related: ['舂 찧을 용', '興 일 흥', '舉 들 거'] },
      { glyph: '尸', reading: '주검 시', strokes: 3, image: '/oracle/尸.png', source: 'https://commons.wikimedia.org/wiki/File:尸-oracle.svg', kind: '상형', ancientNote: '사람이 몸을 굽히거나 옆으로 누운 자세를 나타낸 갑골문입니다.', story: '몸을 굽힌 사람의 옆모습에서 비롯되었습니다. 오늘의 훈음만으로 관련 글자의 의미를 모두 ‘주검’에 연결하지 않도록 주의합니다.', related: ['居 살 거', '屋 집 옥', '展 펼 전'] },
      { glyph: '鬼', reading: '귀신 귀', strokes: 10, image: '/oracle/鬼.png', source: 'https://commons.wikimedia.org/wiki/File:鬼-oracle.svg', kind: '상형', ancientNote: '커다란 머리가면을 쓰고 무릎을 꿇은 사람처럼 표현한 갑골문입니다.', story: '큰 머리나 가면을 쓴 사람의 모습을 본뜬 글자입니다. 귀신·혼·보이지 않는 존재와 관련된 뜻을 만듭니다.', related: ['魂 넋 혼', '魄 넋 백', '魔 마귀 마'] },
    ],
  },
  {
    no: '03', nav: '자연 ① · 하늘과 땅', title: '하늘과 땅을 읽는 글자', focus: '하늘 · 지형 · 빛깔', count: '26',
    objective: '해·달·산·물 같은 자연물의 핵심 윤곽이 글자로 정리되는 과정을 살펴보고, 빛깔 부수까지 자연의 의미 계열을 하나의 지도로 그립니다.',
    range: '日 月 夕 气 雨 風 山 川(巛) 水 火 木 土 田 石 谷 穴 鹵 玉 生 里 白 靑 赤 黑 黃 玄',
    cue: '“정확한 뜻을 몰라도 하늘·땅·빛깔 중 어느 영역의 글자인지 말할 수 있을까요?”',
    activity: '河·炎·森·岩·雪을 물/불/나무/돌/하늘 가족으로 나눠 근거를 말하고, 빛깔 부수 다섯 자로 색 이름 한자어를 만들어 봅니다.',
    characters: [
      { glyph: '日', reading: '날 일', strokes: 4, image: '/oracle/日.svg', source: 'https://commons.wikimedia.org/wiki/File:日-oracle.svg', kind: '상형', ancientNote: '둥근 해 안에 점을 찍어 해임을 나타냈습니다. 뼈에 새기기 쉽게 윤곽이 각졌습니다.', story: '해의 둥근 윤곽 안에 점을 찍어 해를 나타낸 글자입니다. 해에서 낮·날짜·시간의 뜻으로 넓어져 시간과 관련된 글자를 폭넓게 묶습니다.', related: ['明 밝을 명', '時 때 시', '暮 저물 모'] },
      { glyph: '月', reading: '달 월', strokes: 4, image: '/oracle/月.svg', source: 'https://commons.wikimedia.org/wiki/File:月-oracle.svg', kind: '상형', ancientNote: '차고 기우는 초승달의 굽은 윤곽 안에 짧은 선을 더했습니다.', story: '초승달의 모습을 본뜬 글자입니다. 달·한 달·시간의 흐름을 나타내며, 글자 속에서는 고기 육(肉)의 변형과 모양이 겹치므로 주의가 필요합니다.', related: ['朝 아침 조', '期 기약할 기', '望 바랄 망'] },
      { glyph: '夕', reading: '저녁 석', strokes: 3, image: '/oracle/夕.svg', source: 'https://commons.wikimedia.org/wiki/File:夕-oracle.svg', kind: '상형', ancientNote: '갑골문에서 夕은 月과 거의 같은 초승달 모양이었습니다.', story: '해가 진 뒤 떠오른 달로 저녁 무렵을 나타낸 글자입니다. 갑골문에서는 月과 같은 자형을 나눠 쓰다가 뒤에 점 하나 차이로 갈라졌습니다.', related: ['外 바깥 외', '夜 밤 야', '多 많을 다'] },
      { glyph: '气', reading: '기운 기', strokes: 4, image: '/oracle/气.svg', source: 'https://commons.wikimedia.org/wiki/File:气-oracle.svg', kind: '상형', ancientNote: '피어오르는 김이나 구름 기운을 흐르는 세 줄로 나타냈습니다.', story: '눈에 보이지 않는 공기와 김의 흐름을 굽은 선으로 나타낸 글자입니다. 한국 한자어에서는 주로 米를 더한 氣로 쓰고, 气는 부수형으로 다룹니다.', related: ['氣 기운 기', '汽 물끓는김 기'] },
      { glyph: '雨', reading: '비 우', strokes: 8, image: '/oracle/雨.svg', source: 'https://commons.wikimedia.org/wiki/File:雨-oracle.svg', kind: '상형', ancientNote: '하늘을 나타내는 선 아래로 빗방울이 떨어지는 장면입니다.', story: '하늘에서 빗방울이 떨어지는 장면을 그대로 옮긴 글자입니다. 부수로는 눈·구름·번개·이슬 등 하늘에서 내려오는 기상 현상을 묶습니다.', related: ['雪 눈 설', '雲 구름 운', '電 번개 전'] },
      { glyph: '風', reading: '바람 풍', strokes: 9, image: '/oracle/風.svg', source: 'https://commons.wikimedia.org/wiki/File:風-oracle.svg', kind: '형성', ancientNote: '갑골문에서는 봉황새 모양의 글자(鳳)를 빌려 바람을 적었습니다.', story: '보이지 않는 바람을 처음엔 봉황새 鳳으로 빌려 적다가, 凡이 소리를 虫이 뜻 갈래를 맡는 지금의 형성자로 정리되었습니다. 바람·기후·풍속의 뜻을 만듭니다.', related: ['颱 태풍 태', '飄 나부낄 표', '楓 단풍 풍'] },
      { glyph: '山', reading: '메 산', strokes: 3, image: '/oracle/山.svg', source: 'https://commons.wikimedia.org/wiki/File:山-oracle.svg', kind: '상형', ancientNote: '세 봉우리가 나란히 솟은 산줄기의 윤곽입니다.', story: '봉우리 셋이 이어진 산줄기를 본뜬 글자입니다. 산·바위·고개·섬처럼 솟은 지형과 관련된 뜻을 묶습니다.', related: ['岩 바위 암', '峰 봉우리 봉', '島 섬 도'] },
      { glyph: '川', reading: '내 천', strokes: 3, image: '/oracle/川.svg', source: 'https://commons.wikimedia.org/wiki/File:川-oracle.svg', kind: '상형', variant: '巛', variantName: '巛 · 개미허리(부수형)', ancientNote: '양쪽 기슭 사이로 물줄기가 흘러가는 모습입니다.', story: '흐르는 물줄기를 세 가닥 선으로 나타낸 글자입니다. 자전의 부수 표제는 꺾인 모양의 巛(개미허리)이고 川이 그 대표 글자입니다.', related: ['州 고을 주', '巡 돌 순', '順 순할 순'] },
      { glyph: '水', reading: '물 수', strokes: 4, image: '/oracle/水.svg', source: 'https://commons.wikimedia.org/wiki/File:水-oracle.svg', kind: '상형', variant: '氵·氺', variantName: '氵 · 삼수변 / 氺 · 아래물수', ancientNote: '가운데 물줄기와 양옆으로 튀는 물방울을 그렸습니다.', story: '굽이치는 물줄기 좌우로 물방울이 튀는 모습입니다. 왼쪽에서는 氵 세 점으로 줄고, 아래에서는 氺로 모습을 바꿔 물의 뜻을 이어 갑니다.', related: ['江 강 강', '海 바다 해', '洗 씻을 세'] },
      { glyph: '火', reading: '불 화', strokes: 4, image: '/oracle/火.svg', source: 'https://commons.wikimedia.org/wiki/File:火-oracle.svg', kind: '상형', variant: '灬', variantName: '灬 · 연화발', ancientNote: '가운데 큰 불꽃과 양옆으로 튀는 불티를 나타냈습니다.', story: '타오르는 불꽃과 튀는 불티를 본뜬 글자입니다. 글자 아래에서는 灬 네 점으로 납작해져 연화발이라 부르며, 불·열·빛의 뜻을 만듭니다.', related: ['炎 불꽃 염', '燒 사를 소', '熱 더울 열'] },
      { glyph: '木', reading: '나무 목', strokes: 4, image: '/oracle/木.svg', source: 'https://commons.wikimedia.org/wiki/File:木-oracle.svg', kind: '상형', ancientNote: '위로 뻗은 가지와 아래로 내린 뿌리를 함께 그렸습니다.', story: '한 그루 나무의 가지·줄기·뿌리를 모두 담은 글자입니다. 나무의 종류와 재목, 나무로 만든 물건까지 폭넓게 묶습니다.', related: ['林 수풀 림', '根 뿌리 근', '果 실과 과'] },
      { glyph: '土', reading: '흙 토', strokes: 3, image: '/oracle/土.svg', source: 'https://commons.wikimedia.org/wiki/File:土-oracle.svg', kind: '상형', ancientNote: '땅 위에 흙무더기가 소복하게 쌓인 모습입니다.', story: '땅과 그 위에 쌓인 흙덩이를 나타낸 글자입니다. 땅·장소·흙을 쌓고 다루는 일과 관련된 뜻의 단서가 됩니다.', related: ['地 땅 지', '城 성 성', '場 마당 장'] },
      { glyph: '田', reading: '밭 전', strokes: 5, image: '/oracle/田.svg', source: 'https://commons.wikimedia.org/wiki/File:田-oracle.svg', kind: '상형', ancientNote: '네모난 경작지를 이랑길로 나눈 모습을 위에서 내려다봤습니다.', story: '반듯하게 구획한 밭을 위에서 내려다본 글자입니다. 농사짓는 땅에서 출발해 경계·구역의 뜻으로 넓어졌습니다.', related: ['男 사내 남', '界 지경 계', '留 머무를 류'] },
      { glyph: '石', reading: '돌 석', strokes: 5, image: '/oracle/石.svg', source: 'https://commons.wikimedia.org/wiki/File:石-oracle.svg', kind: '상형', ancientNote: '벼랑 아래에 돌덩이가 놓인 모습입니다.', story: '절벽 아래 떨어져 있는 돌덩이를 본뜬 글자입니다. 돌·광물·단단한 것, 돌로 만든 도구와 관련된 뜻을 만듭니다.', related: ['岩 바위 암', '破 깨뜨릴 파', '硏 갈 연'] },
      { glyph: '谷', reading: '골 곡', strokes: 7, image: '/oracle/谷.svg', source: 'https://commons.wikimedia.org/wiki/File:谷-oracle.svg', kind: '회의', ancientNote: '골짜기 입구로 물이 갈라져 흘러나오는 모습입니다.', story: '산 사이로 물이 흘러나오는 골짜기의 입구를 나타낸 글자입니다. 형성자에서는 浴·俗처럼 소리를 빌려주는 쪽으로 자주 쓰입니다.', related: ['浴 목욕할 욕', '俗 풍속 속', '谿 시내 계'] },
      { glyph: '穴', reading: '구멍 혈', strokes: 5, image: '/oracle/穴.svg', source: 'https://commons.wikimedia.org/wiki/File:穴-bigseal.svg', ancientLabel: '대전(大篆)', kind: '상형', ancientNote: '공개 갑골문 도판이 확인되지 않아 대전 자형을 제시합니다. 입구를 갖춘 동굴 집의 윤곽으로 풀이합니다.', story: '땅을 파서 만든 동굴 집의 입구를 본뜬 글자입니다. 구멍·굴·뚫린 공간과 관련된 글자를 위에서 덮듯 묶습니다.', related: ['空 빌 공', '窓 창 창', '究 연구할 구'] },
      { glyph: '鹵', reading: '소금밭 로', strokes: 11, image: '/oracle/鹵.svg', source: 'https://commons.wikimedia.org/wiki/File:鹵-oracle.svg', kind: '상형', ancientNote: '자루 안에 소금 알갱이가 담긴 모습으로 풀이합니다.', story: '소금이 나는 땅과 그 알갱이를 나타낸 글자로 설명합니다. 소금·짠맛과 관련된 글자를 묶는 낯설지만 정직한 부수입니다.', related: ['鹽 소금 염', '鹹 짤 함'] },
      { glyph: '玉', reading: '구슬 옥', strokes: 5, image: '/oracle/玉.svg', source: 'https://commons.wikimedia.org/wiki/File:玉-oracle.svg', kind: '상형', variant: '王', variantName: '王 · 구슬옥변', ancientNote: '구슬 여러 개를 끈으로 꿴 모습입니다.', story: '구슬 세 개를 실로 꿴 모습이며, 점은 나중에 임금 王과 구별하려고 더해졌습니다. 옥·보석·아름답고 귀한 것의 뜻을 만듭니다.', related: ['珠 구슬 주', '理 다스릴 리', '現 나타날 현'] },
      { glyph: '生', reading: '날 생', strokes: 5, image: '/oracle/生.svg', source: 'https://commons.wikimedia.org/wiki/File:生-oracle.svg', kind: '상형·회의', ancientNote: '흙을 뚫고 새싹이 돋아나는 모습입니다.', story: '땅 위로 새싹이 돋는 모습으로 태어남과 자람을 나타낸 글자입니다. 삶·낳음·날것·싱싱함까지 뜻이 넓게 확장됩니다.', related: ['産 낳을 산', '性 성품 성', '星 별 성'] },
      { glyph: '里', reading: '마을 리', strokes: 7, image: '/oracle/里.svg', source: 'https://commons.wikimedia.org/wiki/File:里-bronze.svg', ancientLabel: '금문(金文)', kind: '회의', ancientNote: '공개 갑골문 도판이 확인되지 않아 금문 자형을 제시합니다. 밭(田)과 흙(土)을 합쳐 농사지으며 사는 땅을 나타냈습니다.', story: '밭 田과 흙 土를 합쳐 사람이 모여 사는 마을을 나타낸 글자입니다. 마을에서 거리를 세는 단위(리)로도 뜻이 넓어졌습니다.', related: ['野 들 야', '量 헤아릴 량', '重 무거울 중'] },
      { glyph: '白', reading: '흰 백', strokes: 5, image: '/oracle/白.svg', source: 'https://commons.wikimedia.org/wiki/File:白-oracle.svg', kind: '상형', ancientNote: '무엇을 본떴는지는 햇빛·엄지손톱·쌀알 등 여러 설이 있습니다.', story: '흰빛과 밝음을 나타내는 글자로, 기원에 대해서는 여러 설이 나란히 전합니다. 희다에서 밝히다·아뢰다로 뜻이 넓어졌습니다.', related: ['百 일백 백', '的 과녁 적', '皆 다 개'] },
      { glyph: '靑', reading: '푸를 청', strokes: 8, image: '/oracle/靑.svg', source: 'https://commons.wikimedia.org/wiki/File:青-bronze.svg', ancientLabel: '금문(金文)', kind: '회의', ancientNote: '공개 갑골문 도판이 확인되지 않아 금문 자형을 제시합니다. 돋아난 싹(生)과 광물(丹)을 합쳐 맑고 푸른 빛을 나타낸 것으로 풀이합니다.', story: '싹 生과 광물 丹을 합쳐 갓 돋은 풀빛 같은 푸름을 나타낸 것으로 풀이합니다. 형성자에서 청 계열 소리를 빌려주는 대표 음부이기도 합니다.', related: ['淸 맑을 청', '晴 갤 청', '靜 고요할 정'] },
      { glyph: '赤', reading: '붉을 적', strokes: 7, image: '/oracle/赤.svg', source: 'https://commons.wikimedia.org/wiki/File:赤-oracle.svg', kind: '회의', ancientNote: '큰 사람(大)과 불(火)을 합친 모습입니다.', story: '사람 大와 불 火를 합쳐 크게 타오르는 불의 붉은빛을 나타낸 글자입니다. 붉음에서 맨몸·모자람(赤字)의 뜻으로도 빌려 쓰입니다.', related: ['赦 용서할 사', '赫 빛날 혁'] },
      { glyph: '黑', reading: '검을 흑', strokes: 12, image: '/oracle/黑.svg', source: 'https://commons.wikimedia.org/wiki/File:黑-oracle.svg', kind: '상형·회의', ancientNote: '굴뚝에 그을음이 낀 모습 또는 얼굴에 먹을 새긴 사람으로 풀이합니다.', story: '불 때는 굴뚝에 그을음이 앉은 모습으로 검은빛을 나타냈다고 풀이합니다. 검음·어두움, 그리고 어두운 평판의 뜻까지 묶습니다.', related: ['黙 잠잠할 묵', '點 점 점', '黨 무리 당'] },
      { glyph: '黃', reading: '누를 황', strokes: 12, image: '/oracle/黃.svg', source: 'https://commons.wikimedia.org/wiki/File:黃-oracle.svg', kind: '상형', ancientNote: '허리에 둥근 패옥을 찬 사람의 모습으로 보는 설이 유력합니다.', story: '허리에 옥을 찬 사람을 본떴다는 설이 유력하며, 그 옥빛에서 누런빛의 뜻이 나왔다고 풀이합니다. 땅과 곡식의 빛깔로 이어집니다.', related: ['橫 가로 횡', '廣 넓을 광'] },
      { glyph: '玄', reading: '검을 현', strokes: 5, image: '/oracle/玄.svg', source: 'https://commons.wikimedia.org/wiki/File:玄-bronze.svg', ancientLabel: '금문(金文)', kind: '상형', ancientNote: '공개 갑골문 도판이 확인되지 않아 금문 자형을 제시합니다. 물들이려고 매달아 놓은 실타래를 본뜬 것으로 풀이합니다.', story: '검게 물들인 실타래를 본뜬 것으로 풀이하며, 검붉은빛과 아득함·심오함을 나타냅니다. 幺·糸와 같은 실 계열 자형과 이어집니다.', related: ['玆 이 자', '率 거느릴 솔', '絃 줄 현'] },
    ],
  },
  {
    no: '04', nav: '자연 ② · 동식물', title: '살아 있는 자연의 분류표', focus: '식물 · 짐승 · 날개와 비늘', count: '28',
    objective: '식물·곡물 부수와 동물 부수를 계열별로 분류하고, 처음 보는 글자도 부수만으로 어떤 생물의 갈래인지 좁히는 연습을 합니다.',
    range: '艸 竹 禾 米 麥 黍 麻 瓜 韭 牛 犬 羊 豕 馬 鹿 虎(虍) 豸 鼠 鳥 隹 羽 虫 魚 黽 龍 龜 角 皮',
    cue: '“이 글자는 식물인가요, 네발짐승인가요, 날개나 비늘이 있나요? 근거는 어느 획에 있나요?”',
    activity: '처음 보는 글자를 식물/짐승/새·벌레·물고기 세 바구니에 나눠 담는 부수 생태 분류 게임을 하고, 鳥와 隹처럼 닮은 부수의 차이를 설명합니다.',
    characters: [
      { glyph: '艸', reading: '풀 초', strokes: 6, image: '/oracle/艸.svg', source: 'https://commons.wikimedia.org/wiki/File:艸-seal.svg', ancientLabel: '소전(小篆)', kind: '상형', variant: '艹', variantName: '艹 · 초두머리', ancientNote: '공개 갑골문 도판이 확인되지 않아 소전 자형을 제시합니다. 풀 두 포기가 나란히 돋아난 모습입니다.', story: '돋아난 풀 두 포기를 본뜬 글자입니다. 글자 위에서는 艹 초두머리로 줄어 풀·나물·약재와 관련된 뜻을 엽니다.', related: ['花 꽃 화', '草 풀 초', '藥 약 약'] },
      { glyph: '竹', reading: '대 죽', strokes: 6, image: '/oracle/竹.svg', source: 'https://commons.wikimedia.org/wiki/File:竹-oracle.svg', kind: '상형', variant: '⺮', variantName: '⺮ · 대죽머리', ancientNote: '잎이 달린 대나무 두 줄기를 나란히 그렸습니다.', story: '잎을 늘어뜨린 대나무 두 줄기의 모습입니다. 위에서는 ⺮ 대죽머리가 되어 붓·책·악기 등 대나무로 만든 물건을 묶습니다.', related: ['筆 붓 필', '答 대답 답', '節 마디 절'] },
      { glyph: '禾', reading: '벼 화', strokes: 5, image: '/oracle/禾.svg', source: 'https://commons.wikimedia.org/wiki/File:禾-oracle.svg', kind: '상형', ancientNote: '이삭이 익어 고개를 숙인 곡식 한 포기입니다.', story: '이삭이 여물어 고개 숙인 곡식 한 포기를 본뜬 글자입니다. 곡식·수확·조세처럼 농사에서 나온 뜻을 폭넓게 묶습니다.', related: ['秋 가을 추', '種 씨 종', '稅 세금 세'] },
      { glyph: '米', reading: '쌀 미', strokes: 6, image: '/oracle/米.svg', source: 'https://commons.wikimedia.org/wiki/File:米-oracle.svg', kind: '상형', ancientNote: '이삭 줄기 사이사이에 낟알이 흩어져 있는 모습입니다.', story: '낟알이 흩어진 모습을 본뜬 글자입니다. 곡식의 알갱이·가루·정미된 식량과 관련된 뜻을 만듭니다.', related: ['粉 가루 분', '精 정할 정', '糖 엿 당'] },
      { glyph: '麥', reading: '보리 맥', strokes: 11, image: '/oracle/麥.svg', source: 'https://commons.wikimedia.org/wiki/File:麥-oracle.svg', kind: '상형·회의', ancientNote: '보리 이삭(來) 아래에 발(夂)이 더해진 구조입니다.', story: '보리 이삭을 그린 來가 오다라는 뜻으로 빌려 쓰이자, 발을 더한 麥이 보리의 뜻을 이어받았다고 풀이합니다. 보리·밀과 그 가공식품을 묶습니다.', related: ['麵 국수 면', '麴 누룩 국'] },
      { glyph: '黍', reading: '기장 서', strokes: 12, image: '/oracle/黍.svg', source: 'https://commons.wikimedia.org/wiki/File:黍-oracle.svg', kind: '상형·회의', ancientNote: '이삭이 퍼진 기장 포기와 물(술)을 함께 나타낸 것으로 풀이합니다.', story: '낟알이 흩어지듯 여무는 곡식 기장을 나타낸 글자입니다. 술을 빚던 대표 곡물이라 자형에 물이 더해졌다고 풀이합니다.', related: ['黎 검을 려'] },
      { glyph: '麻', reading: '삼 마', strokes: 11, image: '/oracle/麻.svg', source: 'https://commons.wikimedia.org/wiki/File:麻-bronze.svg', ancientLabel: '금문(金文)', kind: '회의', ancientNote: '공개 갑골문 도판이 확인되지 않아 금문 자형을 제시합니다. 집(广) 안에서 삼 줄기 껍질을 벗겨 널어놓은 모습입니다.', story: '집 안에서 삼 껍질을 벗겨 말리는 장면을 합친 글자입니다. 삼베·마 섬유와 관련되며, 형성자에서는 마 소리를 빌려줍니다.', related: ['磨 갈 마', '摩 문지를 마'] },
      { glyph: '瓜', reading: '오이 과', strokes: 5, image: '/oracle/瓜.svg', source: 'https://commons.wikimedia.org/wiki/File:瓜-bigseal.svg', ancientLabel: '대전(大篆)', kind: '상형', ancientNote: '공개 갑골문 도판이 확인되지 않아 대전 자형을 제시합니다. 덩굴 사이에 열매가 매달린 모습입니다.', story: '덩굴 가운데 열매가 매달린 모습을 본뜬 글자입니다. 오이·박·참외처럼 덩굴에 열리는 열매를 묶습니다.', related: ['瓢 바가지 표', '瓣 꽃잎 판'] },
      { glyph: '韭', reading: '부추 구', strokes: 9, image: '/oracle/韭.svg', source: 'https://commons.wikimedia.org/wiki/File:韭-seal.svg', ancientLabel: '소전(小篆)', kind: '상형', ancientNote: '공개 갑골문 도판이 확인되지 않아 소전 자형을 제시합니다. 땅 위로 부추가 가지런히 자란 모습입니다.', story: '땅 위로 가지런히 자란 부추 포기를 본뜬 글자입니다. 부수 가운데 가장 낯선 축이지만 자형은 그대로 그림입니다.', related: ['韮 부추 구(속자)'] },
      { glyph: '牛', reading: '소 우', strokes: 4, image: '/oracle/牛.svg', source: 'https://commons.wikimedia.org/wiki/File:牛-oracle.svg', kind: '상형', variant: '牜', variantName: '牜 · 소우변', ancientNote: '정면에서 본 소의 머리와 두 뿔을 나타냈습니다.', story: '소의 얼굴과 위로 솟은 두 뿔을 정면에서 본 모습입니다. 왼쪽에서는 牜로 줄어 가축·물건·기르는 일과 이어집니다.', related: ['物 물건 물', '特 특별할 특', '牧 칠 목'] },
      { glyph: '犬', reading: '개 견', strokes: 4, image: '/oracle/犬.svg', source: 'https://commons.wikimedia.org/wiki/File:犬-oracle.svg', kind: '상형', variant: '犭', variantName: '犭 · 개사슴록변', ancientNote: '꼬리를 위로 만 개를 옆에서 본 모습입니다.', story: '꼬리를 만 개의 옆모습을 본뜬 글자입니다. 왼쪽에서는 犭 개사슴록변이 되어 개는 물론 여러 짐승의 성질을 나타냅니다.', related: ['狗 개 구', '獨 홀로 독', '猛 사나울 맹'] },
      { glyph: '羊', reading: '양 양', strokes: 6, image: '/oracle/羊.svg', source: 'https://commons.wikimedia.org/wiki/File:羊-oracle.svg', kind: '상형', ancientNote: '정면에서 본 양의 머리와 굽은 두 뿔입니다.', story: '굽은 뿔이 달린 양의 머리를 정면에서 본 모습입니다. 옛사람에게 좋고 상서로운 짐승이어서 美·善 같은 글자에도 들어갑니다.', related: ['美 아름다울 미', '群 무리 군', '義 옳을 의'] },
      { glyph: '豕', reading: '돼지 시', strokes: 7, image: '/oracle/豕.svg', source: 'https://commons.wikimedia.org/wiki/File:豕-oracle.svg', kind: '상형', ancientNote: '통통한 몸통과 짧은 다리, 처진 꼬리의 돼지 옆모습입니다.', story: '살진 돼지의 옆모습을 본뜬 글자입니다. 집 家의 지붕 아래 들어 있을 만큼 옛 살림과 가까운 짐승이었습니다.', related: ['家 집 가', '豚 돼지 돈', '象 코끼리 상'] },
      { glyph: '馬', reading: '말 마', strokes: 10, image: '/oracle/馬.svg', source: 'https://commons.wikimedia.org/wiki/File:馬-oracle.svg', kind: '상형', ancientNote: '갈기와 큰 눈, 네 다리와 꼬리가 뚜렷한 말의 옆모습입니다.', story: '긴 얼굴과 날리는 갈기, 네 다리를 갖춘 말의 옆모습입니다. 타고 달리는 일과 말의 종류·상태를 묶습니다.', related: ['駐 머무를 주', '騎 말 탈 기', '驚 놀랄 경'] },
      { glyph: '鹿', reading: '사슴 록', strokes: 11, image: '/oracle/鹿.svg', source: 'https://commons.wikimedia.org/wiki/File:鹿-oracle.svg', kind: '상형', ancientNote: '가지 친 뿔과 가는 다리를 갖춘 사슴의 옆모습입니다.', story: '가지 친 뿔이 돋보이는 사슴의 옆모습입니다. 사슴 종류의 이름과 곱고 빼어난 것의 뜻으로 이어집니다.', related: ['麗 고울 려', '麓 산기슭 록', '麟 기린 린'] },
      { glyph: '虎', reading: '범 호', strokes: 8, image: '/oracle/虎.svg', source: 'https://commons.wikimedia.org/wiki/File:虎-oracle.svg', kind: '상형', variant: '虍', variantName: '虍 · 범호엄(부수형)', ancientNote: '큰 입과 줄무늬 몸통을 지닌 호랑이를 세워서 그렸습니다.', story: '입을 벌린 호랑이의 모습을 본뜬 글자입니다. 부수 표제는 머리만 남긴 虍(범호엄)이며 處·虛의 윗부분에서 만납니다.', related: ['處 곳 처', '虛 빌 허', '號 이름 호'] },
      { glyph: '豸', reading: '벌레 치', strokes: 7, image: '/oracle/豸.svg', source: 'https://commons.wikimedia.org/wiki/File:豸-oracle.svg', kind: '상형', ancientNote: '입을 벌리고 등을 웅크린 맹수의 옆모습입니다.', story: '등이 길고 발톱이 날카로운 맹수가 웅크린 모습입니다. 훈음과 달리 실제로는 표범·승냥이 같은 짐승 글자를 묶습니다.', related: ['豹 표범 표', '豺 승냥이 시', '貌 모양 모'] },
      { glyph: '鼠', reading: '쥐 서', strokes: 13, image: '/oracle/鼠.svg', source: 'https://commons.wikimedia.org/wiki/File:鼠-oracle.svg', kind: '상형', ancientNote: '이빨을 드러낸 머리와 발, 긴 꼬리를 갖춘 쥐의 모습입니다.', story: '앞니와 긴 꼬리가 강조된 쥐를 본뜬 글자입니다. 쥐 종류와 구멍에 사는 작은 짐승의 이름을 묶습니다.', related: ['竄 숨을 찬'] },
      { glyph: '鳥', reading: '새 조', strokes: 11, image: '/oracle/鳥.svg', source: 'https://commons.wikimedia.org/wiki/File:鳥-oracle.svg', kind: '상형', ancientNote: '부리·눈·날개·꼬리를 갖춘 새의 옆모습입니다.', story: '부리와 눈, 날개와 긴 꼬리를 갖춘 새의 옆모습입니다. 새의 이름과 날개 있는 생물을 폭넓게 분류합니다.', related: ['鳴 울 명', '鶴 학 학', '鷄 닭 계'] },
      { glyph: '隹', reading: '새 추', strokes: 8, image: '/oracle/隹.svg', source: 'https://commons.wikimedia.org/wiki/File:隹-oracle.svg', kind: '상형', ancientNote: '꽁지가 짧은 새를 옆에서 본 모습입니다.', story: '꽁지 짧은 새를 본뜬 또 하나의 새 부수입니다. 集·雜처럼 새가 직접 보이지 않는 글자에서도 뜻의 뿌리로 남아 있습니다.', related: ['集 모을 집', '雜 섞일 잡', '難 어려울 난'] },
      { glyph: '羽', reading: '깃 우', strokes: 6, image: '/oracle/羽.svg', source: 'https://commons.wikimedia.org/wiki/File:羽-oracle.svg', kind: '상형', ancientNote: '깃털 두 가닥을 나란히 그렸습니다.', story: '새의 깃털 두 가닥을 나란히 놓은 모습입니다. 깃·날개·나는 일과 관련된 뜻을 만들며, 習에서는 나는 연습의 장면이 남아 있습니다.', related: ['習 익힐 습', '翼 날개 익', '翁 늙은이 옹'] },
      { glyph: '虫', reading: '벌레 훼', strokes: 6, image: '/oracle/虫.svg', source: 'https://commons.wikimedia.org/wiki/File:虫-oracle.svg', kind: '상형', ancientNote: '머리가 세모진 뱀이 몸을 구부린 모습입니다.', story: '본래 뱀을 그린 글자로 훼라고 읽으며, 오늘날 벌레 전체는 세 개를 겹친 蟲(충)으로 씁니다. 벌레·뱀·작은 생물을 묶는 부수입니다.', related: ['蛇 뱀 사', '蝶 나비 접', '蟲 벌레 충'] },
      { glyph: '魚', reading: '물고기 어', strokes: 11, image: '/oracle/魚.svg', source: 'https://commons.wikimedia.org/wiki/File:魚-oracle.svg', kind: '상형', ancientNote: '머리·비늘 몸통·지느러미·꼬리를 갖춘 물고기입니다.', story: '비늘과 지느러미까지 그린 물고기의 옆모습입니다. 물고기의 이름과 물에 사는 생물, 고기잡이와 관련된 뜻을 묶습니다.', related: ['鮮 고울 선', '鯨 고래 경', '漁 고기잡을 어'] },
      { glyph: '黽', reading: '맹꽁이 맹', strokes: 13, image: '/oracle/黽.svg', source: 'https://commons.wikimedia.org/wiki/File:黽-oracle.svg', kind: '상형', ancientNote: '큰 배와 네 다리를 벌린 개구리를 정면에서 본 모습입니다.', story: '배가 불룩한 개구리를 정면에서 본 모습입니다. 개구리·자라 같은 물가 생물을 묶으며, 힘쓸 민으로도 읽습니다.', related: ['鼈 자라 별'] },
      { glyph: '龍', reading: '용 룡', strokes: 16, image: '/oracle/龍.svg', source: 'https://commons.wikimedia.org/wiki/File:龍-oracle.svg', kind: '상형', ancientNote: '뿔 달린 머리와 굽이치는 긴 몸을 지닌 상상의 동물입니다.', story: '뿔과 큰 입, 굽이치는 몸을 지닌 상상 속 동물 용을 그렸습니다. 왕과 비·구름 등 신령한 힘과 관련된 뜻으로 이어집니다.', related: ['籠 대바구니 롱', '寵 사랑할 총'] },
      { glyph: '龜', reading: '거북 귀', strokes: 16, image: '/oracle/龜.svg', source: 'https://commons.wikimedia.org/wiki/File:龜-oracle.svg', kind: '상형', ancientNote: '등딱지 무늬와 머리·꼬리·발이 모두 보이는 거북입니다.', story: '등딱지와 네 발이 그대로 보이는 거북의 모습입니다. 갑골문을 새기던 바로 그 거북 배딱지를 떠올리게 하는 부수입니다.', related: ['龜鑑 귀감(단어)'] },
      { glyph: '角', reading: '뿔 각', strokes: 7, image: '/oracle/角.svg', source: 'https://commons.wikimedia.org/wiki/File:角-oracle.svg', kind: '상형', ancientNote: '결이 새겨진 짐승의 뿔 하나를 그렸습니다.', story: '무늬결이 있는 짐승의 뿔을 본뜬 글자입니다. 뿔로 만든 도구·찌르고 겨루는 일에서 모서리·각도의 뜻으로 넓어졌습니다.', related: ['解 풀 해', '觸 닿을 촉'] },
      { glyph: '皮', reading: '가죽 피', strokes: 5, image: '/oracle/皮.svg', source: 'https://commons.wikimedia.org/wiki/File:皮-bronze.svg', ancientLabel: '금문(金文)', kind: '회의', ancientNote: '공개 갑골문 도판이 확인되지 않아 금문 자형을 제시합니다. 손(又)으로 짐승의 가죽을 벗겨 내는 장면입니다.', story: '손으로 가죽을 벗겨 내는 장면을 합친 글자입니다. 껍질·표면의 뜻을 만들고, 형성자에서는 파·피 계열 소리를 빌려줍니다.', related: ['波 물결 파', '疲 피곤할 피', '破 깨뜨릴 파'] },
    ],
  },
  {
    no: '05', nav: '생활과 도구', title: '사람이 만든 것들의 흔적', focus: '집 · 그릇 · 옷감 · 연장', count: '30',
    objective: '집·그릇·옷감·수레·무기 같은 생활 도구가 한자 속에 어떤 모습으로 남았는지 확인하고, 물건의 쓰임과 글자의 뜻을 연결합니다.',
    range: '宀 广 戶 門 高 瓦 食 甘 皿 豆 缶 鬲 鼎 酉 衣 巾 糸 网 革 韋 車 舟 金 貝 斤 弓 矢 戈 殳 鼓',
    cue: '“도구의 생김새와 쓰임 중 무엇이 글자에 더 강하게 남았나요?”',
    activity: '그릇 부수 皿·豆·缶·鬲·鼎을 실물 사진과 짝지어 보고, 무기 부수 弓·矢·戈·殳의 쓰임을 몸짓으로 설명합니다.',
    characters: [
      { glyph: '宀', reading: '집 면', strokes: 3, image: '/oracle/宀.svg', source: 'https://commons.wikimedia.org/wiki/File:宀-oracle.svg', kind: '상형', ancientNote: '지붕과 양쪽 벽이 있는 집의 단면입니다.', story: '지붕이 덮인 집의 단면을 본뜬 글자로, 갓머리라고 부릅니다. 집 안에서 일어나는 일과 머무는 상태를 폭넓게 묶습니다.', related: ['家 집 가', '室 집 실', '安 편안 안'] },
      { glyph: '广', reading: '집 엄', strokes: 3, image: '/oracle/广.svg', source: 'https://commons.wikimedia.org/wiki/File:广-bronze.svg', ancientLabel: '금문(金文)', kind: '상형', ancientNote: '공개 갑골문 도판이 확인되지 않아 금문 자형을 제시합니다. 벼랑이나 언덕에 기대어 지은, 한쪽이 트인 집입니다.', story: '언덕에 기대어 지어 한쪽 벽이 없는 집의 모습으로, 엄호라고 부릅니다. 창고·마당처럼 넓게 튼 건물과 관련된 글자를 위에서 덮습니다.', related: ['店 가게 점', '庭 뜰 정', '廣 넓을 광'] },
      { glyph: '戶', reading: '지게 호', strokes: 4, image: '/oracle/戶.svg', source: 'https://commons.wikimedia.org/wiki/File:戶-oracle.svg', kind: '상형', ancientNote: '한 짝짜리 문의 모습으로, 門의 절반입니다.', story: '한 짝으로 여닫는 외짝 문을 본뜬 글자입니다. 문에서 집·집안이라는 뜻으로 넓어져 지금도 호적·가구를 세는 말에 남아 있습니다.', related: ['房 방 방', '所 바 소', '扉 사립문 비'] },
      { glyph: '門', reading: '문 문', strokes: 8, image: '/oracle/門.svg', source: 'https://commons.wikimedia.org/wiki/File:門-oracle.svg', kind: '상형', ancientNote: '좌우 두 짝으로 여닫는 대문을 정면에서 그렸습니다.', story: '두 짝 대문을 정면에서 본 모습입니다. 드나드는 곳·사이·닫고 여는 일과 관련된 글자를 바깥에서 감싸듯 묶습니다.', related: ['間 사이 간', '開 열 개', '閉 닫을 폐'] },
      { glyph: '高', reading: '높을 고', strokes: 10, image: '/oracle/高.svg', source: 'https://commons.wikimedia.org/wiki/File:高-oracle.svg', kind: '상형', ancientNote: '성문 위로 높이 솟은 망루의 모습입니다.', story: '성문 위에 층층이 올린 망루를 본뜬 글자입니다. 높이·뛰어남의 뜻을 만들고, 형성자에서는 고 계열 소리를 빌려줍니다.', related: ['稿 원고 고', '豪 호걸 호'] },
      { glyph: '瓦', reading: '기와 와', strokes: 5, image: '/oracle/瓦.svg', source: 'https://commons.wikimedia.org/wiki/File:瓦-bigseal.svg', ancientLabel: '대전(大篆)', kind: '상형', ancientNote: '공개 갑골문 도판이 확인되지 않아 대전 자형을 제시합니다. 기와 두 장이 서로 맞물린 모습입니다.', story: '지붕 위에서 암키와와 수키와가 맞물린 모습입니다. 기와·질그릇 등 흙을 구워 만든 물건을 묶습니다.', related: ['甁 병 병', '甕 독 옹'] },
      { glyph: '食', reading: '밥 식', strokes: 9, image: '/oracle/食.svg', source: 'https://commons.wikimedia.org/wiki/File:食-oracle.svg', kind: '상형·회의', variant: '飠', variantName: '飠 · 밥식변', ancientNote: '뚜껑이 덮인 밥그릇에 밥이 담긴 모습입니다.', story: '뚜껑 있는 그릇에 담긴 밥을 본뜬 글자입니다. 왼쪽에서는 飠 밥식변이 되어 먹고 마시고 기르는 일을 나타냅니다.', related: ['飯 밥 반', '飮 마실 음', '養 기를 양'] },
      { glyph: '甘', reading: '달 감', strokes: 5, image: '/oracle/甘.svg', source: 'https://commons.wikimedia.org/wiki/File:甘-oracle.svg', kind: '지사', ancientNote: '입(口) 안에 단것을 머금은 것을 짧은 선으로 표시했습니다.', story: '입 안에 맛있는 것을 머금은 모습을 나타낸 지사자입니다. 단맛에서 달갑다·기꺼이의 뜻으로 넓어졌습니다.', related: ['甛 달 첨', '某 아무 모'] },
      { glyph: '皿', reading: '그릇 명', strokes: 5, image: '/oracle/皿.svg', source: 'https://commons.wikimedia.org/wiki/File:皿-oracle.svg', kind: '상형', ancientNote: '굽이 달린 얕은 그릇을 옆에서 본 모습입니다.', story: '받침 굽이 있는 그릇을 옆에서 본 모습입니다. 담다·채우다처럼 그릇에서 일어나는 일을 아래에서 받칩니다.', related: ['益 더할 익', '盛 담을 성', '盜 도둑 도'] },
      { glyph: '豆', reading: '콩 두', strokes: 7, image: '/oracle/豆.svg', source: 'https://commons.wikimedia.org/wiki/File:豆-oracle.svg', kind: '상형', ancientNote: '굽이 높은 제사 그릇의 모습입니다.', story: '본래 굽 높은 제사 그릇을 그린 글자이며, 콩의 뜻은 나중에 빌려 쓴 것입니다. 그릇과 콩, 두 갈래의 뜻을 모두 만납니다.', related: ['豊 풍성할 풍', '頭 머리 두', '登 오를 등'] },
      { glyph: '缶', reading: '장군 부', strokes: 6, image: '/oracle/缶.svg', source: 'https://commons.wikimedia.org/wiki/File:缶-oracle.svg', kind: '상형', ancientNote: '배가 부르고 주둥이가 좁은 질그릇과 뚜껑입니다.', story: '물·술을 담던 배부른 질그릇 장군을 본뜬 글자입니다. 질그릇이 깨지거나 이지러지는 일과 관련된 글자를 묶습니다.', related: ['缺 이지러질 결'] },
      { glyph: '鬲', reading: '솥 력', strokes: 10, image: '/oracle/鬲.svg', source: 'https://commons.wikimedia.org/wiki/File:鬲-oracle.svg', kind: '상형', ancientNote: '다리 속이 비어 있는 세발솥의 모습입니다.', story: '다리 속까지 비어 물이 빨리 끓는 세발솥을 본뜬 글자입니다. 삶고 찌는 일과 관련되며, 형성자에서는 격 소리를 빌려줍니다.', related: ['隔 사이 뜰 격', '融 녹을 융'] },
      { glyph: '鼎', reading: '솥 정', strokes: 13, image: '/oracle/鼎.svg', source: 'https://commons.wikimedia.org/wiki/File:鼎-oracle.svg', kind: '상형', ancientNote: '두 귀와 세 발이 달린 큰 솥의 모습입니다.', story: '두 귀와 세 발을 갖춘 청동 솥을 본뜬 글자입니다. 제사와 권위의 상징이어서 나라의 보물을 뜻하는 말에도 쓰였습니다.', related: ['則 법칙 칙', '員 인원 원'] },
      { glyph: '酉', reading: '닭 유', strokes: 7, image: '/oracle/酉.svg', source: 'https://commons.wikimedia.org/wiki/File:酉-oracle.svg', kind: '상형', ancientNote: '술이 담긴 항아리의 모습입니다.', story: '술을 빚어 담는 항아리를 본뜬 글자입니다. 부수로는 술·발효·익힘의 뜻을 맡고, 띠 동물 닭의 뜻은 빌려 쓴 것입니다.', related: ['酒 술 주', '醉 취할 취', '醫 의원 의'] },
      { glyph: '衣', reading: '옷 의', strokes: 6, image: '/oracle/衣.svg', source: 'https://commons.wikimedia.org/wiki/File:衣-oracle.svg', kind: '상형', variant: '衤', variantName: '衤 · 옷의변', ancientNote: '옷깃이 포개지고 소매가 양옆으로 펼쳐진 웃옷입니다.', story: '깃을 여민 웃옷의 모습을 본뜬 글자입니다. 왼쪽에서는 衤 옷의변이 되어 입고 짓고 겹치는 일을 나타냅니다.', related: ['初 처음 초', '被 입을 피', '製 지을 제'] },
      { glyph: '巾', reading: '수건 건', strokes: 3, image: '/oracle/巾.svg', source: 'https://commons.wikimedia.org/wiki/File:巾-oracle.svg', kind: '상형', ancientNote: '허리띠에 드리운 천 조각의 모습입니다.', story: '허리에 차고 드리운 천을 본뜬 글자입니다. 천으로 만든 물건, 장막·모자·베와 관련된 뜻을 묶습니다.', related: ['布 베 포', '帳 장막 장', '帽 모자 모'] },
      { glyph: '糸', reading: '실 사', strokes: 6, image: '/oracle/糸.svg', source: 'https://commons.wikimedia.org/wiki/File:糸-oracle.svg', kind: '상형', variant: '糹', variantName: '糹 · 실사변', ancientNote: '명주실을 꼬아 묶은 실타래의 모습입니다.', story: '실을 꼬아 놓은 실타래를 본뜬 글자입니다. 실·끈·엮고 잇는 일과 관련된 큰 부수 가족을 이룹니다.', related: ['線 줄 선', '紙 종이 지', '約 맺을 약'] },
      { glyph: '网', reading: '그물 망', strokes: 6, image: '/oracle/网.svg', source: 'https://commons.wikimedia.org/wiki/File:网-oracle.svg', kind: '상형', variant: '罒', variantName: '罒 · 그물망머리', ancientNote: '틀에 그물코가 얽혀 있는 모습입니다.', story: '그물코가 얽힌 그물을 본뜬 글자입니다. 글자 위에서는 罒로 눕고, 잡다·가두다·벌하다의 뜻과 이어집니다.', related: ['罪 허물 죄', '置 둘 치', '羅 벌일 라'] },
      { glyph: '革', reading: '가죽 혁', strokes: 9, image: '/oracle/革.svg', source: 'https://commons.wikimedia.org/wiki/File:革-oracle.svg', kind: '상형', ancientNote: '머리부터 꼬리까지 벗겨 활짝 펼쳐 말리는 가죽입니다.', story: '벗긴 가죽을 활짝 펼쳐 말리는 모습입니다. 무두질로 새것을 만든다는 데서 고치다·바꾸다의 뜻이 나왔습니다.', related: ['靴 신 화', '鞭 채찍 편'] },
      { glyph: '韋', reading: '다룸가죽 위', strokes: 9, image: '/oracle/韋.svg', source: 'https://commons.wikimedia.org/wiki/File:韋-oracle.svg', kind: '회의', ancientNote: '성곽 둘레를 발이 엇갈려 도는 모습입니다.', story: '성 둘레를 도는 발을 그려 에워싸다를 나타냈고, 밟아 부드럽게 무두질한 가죽의 뜻으로 쓰이게 되었습니다. 皮·革과 함께 가죽 삼형제를 이룹니다.', related: ['偉 클 위', '圍 에워쌀 위', '衛 지킬 위'] },
      { glyph: '車', reading: '수레 거', strokes: 7, image: '/oracle/車.svg', source: 'https://commons.wikimedia.org/wiki/File:車-oracle.svg', kind: '상형', ancientNote: '바퀴·축·몸체를 갖춘 수레를 위에서 내려다봤습니다.', story: '수레를 위에서 내려다본 모습으로, 지금 자형에는 바퀴와 축이 남았습니다. 탈것·바퀴·실어 나르는 일을 묶습니다.', related: ['軍 군사 군', '輪 바퀴 륜', '轉 구를 전'] },
      { glyph: '舟', reading: '배 주', strokes: 6, image: '/oracle/舟.svg', source: 'https://commons.wikimedia.org/wiki/File:舟-oracle.svg', kind: '상형', ancientNote: '통나무배의 몸통과 안쪽 칸을 위에서 본 모습입니다.', story: '길쭉한 배와 안쪽 칸막이를 위에서 본 모습입니다. 배·물길·건너는 일과 관련된 뜻을 만듭니다.', related: ['船 배 선', '航 배 항', '般 일반 반'] },
      { glyph: '金', reading: '쇠 금', strokes: 8, image: '/oracle/金.svg', source: 'https://commons.wikimedia.org/wiki/File:金-bronze.svg', ancientLabel: '금문(金文)', kind: '형성·상형', variant: '釒', variantName: '釒 · 쇠금변', ancientNote: '공개 갑골문 도판이 확인되지 않아 금문 자형을 제시합니다. 거푸집과 그 속의 쇳덩이를 나타낸 것으로 풀이합니다.', story: '거푸집 속 쇳덩이를 나타낸 것으로 풀이하는 글자입니다. 금속·돈·쇠로 만든 도구를 묶고, 성씨로 읽을 때는 김이 됩니다.', related: ['銀 은 은', '鐵 쇠 철', '錢 돈 전'] },
      { glyph: '貝', reading: '조개 패', strokes: 7, image: '/oracle/貝.svg', source: 'https://commons.wikimedia.org/wiki/File:貝-oracle.svg', kind: '상형', ancientNote: '값비싼 조개껍데기의 갈라진 무늬를 그렸습니다.', story: '화폐로 쓰이던 조개껍데기를 본뜬 글자입니다. 재물·값·사고파는 일 등 돈과 관련된 뜻을 도맡습니다.', related: ['財 재물 재', '買 살 매', '貧 가난할 빈'] },
      { glyph: '斤', reading: '도끼 근', strokes: 4, image: '/oracle/斤.svg', source: 'https://commons.wikimedia.org/wiki/File:斤-oracle.svg', kind: '상형', ancientNote: '자루 끝에 날이 달린 도끼의 모습입니다.', story: '자루 달린 도끼를 본뜬 글자입니다. 찍고 끊는 일과 이어지며, 고기 한 근처럼 무게 단위로도 빌려 쓰입니다.', related: ['新 새 신', '斷 끊을 단', '折 꺾을 절'] },
      { glyph: '弓', reading: '활 궁', strokes: 3, image: '/oracle/弓.svg', source: 'https://commons.wikimedia.org/wiki/File:弓-oracle.svg', kind: '상형', ancientNote: '시위를 건 활의 굽은 몸통입니다.', story: '굽은 활의 몸통을 본뜬 글자입니다. 당기고 튕기는 힘, 굽은 모양과 관련된 뜻을 만듭니다.', related: ['引 끌 인', '強 강할 강', '弱 약할 약'] },
      { glyph: '矢', reading: '화살 시', strokes: 5, image: '/oracle/矢.svg', source: 'https://commons.wikimedia.org/wiki/File:矢-oracle.svg', kind: '상형', ancientNote: '화살촉·살대·깃을 갖춘 화살입니다.', story: '촉과 깃이 달린 화살을 본뜬 글자입니다. 곧고 빠른 것의 비유로 쓰이며, 재는 도구의 뜻으로도 이어집니다.', related: ['知 알 지', '短 짧을 단', '矯 바로잡을 교'] },
      { glyph: '戈', reading: '창 과', strokes: 4, image: '/oracle/戈.svg', source: 'https://commons.wikimedia.org/wiki/File:戈-oracle.svg', kind: '상형', ancientNote: '긴 자루 끝에 가로 날이 달린 창입니다.', story: '가로 날이 달린 옛 창을 본뜬 글자입니다. 전쟁·베기와 관련되며, 我·成처럼 뜻이 멀어 보이는 글자에도 자형이 남아 있습니다.', related: ['戰 싸움 전', '成 이룰 성', '我 나 아'] },
      { glyph: '殳', reading: '몽둥이 수', strokes: 4, image: '/oracle/殳.svg', source: 'https://commons.wikimedia.org/wiki/File:殳-oracle.svg', kind: '회의', ancientNote: '손(又)에 긴 몽둥이를 든 모습입니다.', story: '손에 몽둥이를 들고 치는 모습을 합친 글자입니다. 치다·부수다의 뜻을 오른쪽에서 더하며 갖은등글월문이라 부릅니다.', related: ['段 층계 단', '殺 죽일 살', '毁 헐 훼'] },
      { glyph: '鼓', reading: '북 고', strokes: 13, image: '/oracle/鼓.svg', source: 'https://commons.wikimedia.org/wiki/File:鼓-oracle.svg', kind: '회의', ancientNote: '북틀에 세운 북을 채를 들고 치는 장면입니다.', story: '세워 놓은 북(壴)을 손에 채를 들고 치는 장면입니다. 북소리처럼 두드려 힘을 북돋우는 뜻으로 넓어졌습니다.', related: ['壴 세울 주', '攴 칠 복'] },
    ],
  },
  {
    no: '06', nav: '행동과 사회', title: '움직임과 관계를 읽다', focus: '말 · 보기 · 이동 · 힘', count: '22',
    objective: '행동을 나타내는 부수가 문장 속에서 뜻의 방향을 어떻게 결정하는지 확인합니다.',
    range: '言 見 行 走 辵 力 攴 攵 立 止 曰 欠 攵 彳 夂 夊 廴 廾 弋 弓 斗 文',
    cue: '“이 글자의 주인공은 말하고 있나요, 보고 있나요, 움직이고 있나요?”',
    activity: '言·見·辵·力 네 부수만 보고 낯선 글자의 ‘행동 범주’를 먼저 맞힙니다.',
    characters: [
      { glyph: '言', reading: '말씀 언', strokes: 7, kind: '지사·상형', variant: '訁', story: '입에서 말이 여러 겹으로 나오는 모습을 나타낸 것으로 풀이합니다. 말·기록·의사소통을 나타냅니다.', related: ['語 말씀 어', '記 기록할 기', '談 말씀 담'] },
      { glyph: '見', reading: '볼 견', strokes: 7, kind: '회의', story: '큰 눈을 가진 사람이 서 있는 모습으로, 사람이 눈으로 본다는 뜻을 합쳐 만들었습니다.', related: ['視 볼 시', '観 볼 관', '現 나타날 현'] },
      { glyph: '走', reading: '달릴 주', strokes: 7, kind: '상형·회의', story: '사람이 팔을 흔들며 달리는 모습과 발을 나타내는 요소가 합쳐진 글자입니다.', related: ['起 일어날 기', '超 넘을 초', '越 넘을 월'] },
      { glyph: '辵', reading: '쉬엄쉬엄 갈 착', strokes: 7, kind: '회의', variant: '辶', story: '길을 뜻하는 요소와 발걸음을 합쳐 길을 따라 간다는 뜻을 나타냅니다. 글자에서는 주로 辶로 보입니다.', related: ['近 가까울 근', '道 길 도', '進 나아갈 진'] },
      { glyph: '力', reading: '힘 력', strokes: 2, kind: '상형', story: '힘을 주어 사용하는 농기구의 굽은 모습에서 힘의 뜻이 나왔다고 설명합니다.', related: ['功 공 공', '動 움직일 동', '助 도울 조'] },
      { glyph: '立', reading: '설 립', strokes: 5, kind: '지사·상형', story: '사람이 땅 위에 두 발을 딛고 선 모습을 단순화했습니다. 서기·세우기·자리 잡기의 뜻을 품습니다.', related: ['位 자리 위', '章 글 장', '音 소리 음'] },
    ],
  },
  {
    no: '07', nav: '형태가 변하는 부수', title: '자리 따라 옷을 갈아입다', focus: '변형 부수 · 위치 · 압축', count: '22',
    objective: '같은 부수가 한자의 왼쪽·아래·위에서 다른 모습으로 변한다는 규칙을 익힙니다.',
    range: '人→亻 水→氵 心→忄·⺗ 手→扌 火→灬 艸→艹 犬→犭 衣→衤 言→訁 金→釒 糸→糹 食→飠 刀→刂 阜→阝 邑→阝 肉→月',
    cue: '“모양은 달라졌지만 같은 부수라는 증거를 어디서 찾을 수 있나요?”',
    activity: '기본형 카드를 변형형 카드에 짝짓고, 실제 한자에서 어느 자리에 있는지 표시합니다.',
    characters: [
      { glyph: '人', reading: '사람 인', strokes: 2, variant: '亻', kind: '변형', story: '왼쪽 좁은 자리에 들어가면 오른쪽 획을 세워 亻가 됩니다. 글자 전체의 균형을 위한 압축입니다.', related: ['休', '住', '作'] },
      { glyph: '水', reading: '물 수', strokes: 4, variant: '氵', kind: '변형', story: '왼쪽에서는 흐르는 물의 세 점만 남겨 氵가 됩니다. 모양이 줄어도 물의 의미는 그대로 유지됩니다.', related: ['河', '海', '洗'] },
      { glyph: '心', reading: '마음 심', strokes: 4, variant: '忄·⺗', kind: '변형', story: '왼쪽에서는 세로로 긴 忄, 아래에서는 납작한 ⺗ 또는 心으로 자리의 모양에 맞춥니다.', related: ['情', '想', '慕'] },
      { glyph: '手', reading: '손 수', strokes: 4, variant: '扌', kind: '변형', story: '왼쪽에서 세 획의 扌로 줄어 손의 동작을 나타냅니다. 손이 직접 보이지 않아도 의미는 남습니다.', related: ['打', '投', '指'] },
      { glyph: '火', reading: '불 화', strokes: 4, variant: '灬', kind: '변형', story: '글자 아래에서는 네 점으로 퍼진 灬가 됩니다. 불꽃이나 열의 흔적을 아래쪽에 납작하게 배치합니다.', related: ['熱', '照', '無'] },
      { glyph: '艸', reading: '풀 초', strokes: 6, variant: '艹', kind: '변형', story: '글자 위에서는 두 묶음의 새싹을 간결한 艹로 줄입니다. 식물·풀·약재와 관련된 뜻을 엽니다.', related: ['花', '草', '薬'] },
    ],
  },
  {
    no: '08', nav: '낯선 부수', title: '작지만 중요한 분류 표지', focus: '저빈도 · 형태 구별 · 사전 찾기', count: '25',
    objective: '자주 보이지 않는 부수를 억지로 암기하기보다, 생김새를 구별하고 사전에서 찾는 법을 익힙니다.',
    range: '匕 匚 匸 冂 冖 凵 夂 夊 宀 尸 屮 廾 彐 弋 彡 廴 尢 屮 巛 幺 广 廾 廿 爻 爿',
    cue: '“뜻을 외우지 못해도 서로 다른 모양으로 구별할 수 있나요?”',
    activity: '닮은꼴 부수 匚·匸, 冂·凵, 夂·夊를 확대 비교하고 획의 열린 방향을 말합니다.',
    characters: [
      { glyph: '匕', reading: '비수 비', strokes: 2, kind: '상형', story: '짧은 칼이나 숟가락처럼 굽은 도구의 모양으로 설명됩니다. 자형이 비슷한 七과 구별합니다.', related: ['化 될 화', '北 북녘 북', '匙 숟가락 시'] },
      { glyph: '匚', reading: '상자 방', strokes: 2, kind: '상형', story: '물건을 담는 상자를 옆이 열린 네모꼴로 나타냈습니다. 오른쪽이 열린 모양을 먼저 기억합니다.', related: ['匠 장인 장', '匣 갑 갑', '匪 아닐 비'] },
      { glyph: '冂', reading: '멀 경', strokes: 2, kind: '상형', story: '멀리 둘러싼 경계나 바깥 테두리를 나타내는 부수입니다. 아래가 열려 있는 모양을 관찰합니다.', related: ['同 한가지 동', '円 둥글 원', '冊 책 책'] },
      { glyph: '冖', reading: '덮을 멱', strokes: 2, kind: '상형', story: '천이나 덮개가 위에서 내려와 가리는 모습을 나타냈습니다. 宀보다 한 획 적고 가운데 점이 없습니다.', related: ['冠 갓 관', '冥 어두울 명', '写 베낄 사'] },
      { glyph: '宀', reading: '집 면', strokes: 3, kind: '상형', story: '지붕과 처마가 있는 집의 윗부분을 본뜬 글자입니다. 집 안의 사람·물건·상태를 나타냅니다.', related: ['家 집 가', '室 집 실', '安 편안 안'] },
      { glyph: '尸', reading: '주검 시', strokes: 3, kind: '상형', story: '사람이 몸을 굽히거나 앉은 옆모습에서 비롯된 자형입니다. 현재 훈음만으로 모든 관련 글자의 뜻을 단정하지 않습니다.', related: ['居 살 거', '屋 집 옥', '展 펼 전'] },
    ],
  },
  {
    no: '09', nav: '나머지 부수 · 구조', title: '부수와 소리 단서를 나누다', focus: '형성자 · 의미부 · 음부', count: '29',
    objective: '남은 저빈도 부수를 정리하고, 한 글자 안에서 뜻을 맡는 부분과 소리를 빌려주는 부분을 구별합니다.',
    range: '酉 靑 韋 頁 飛 首 香 馬 骨 高 鬥 鬯 鬲 鬼 魚 鳥 鹵 鹿 麥 麻 黃 黍 黑 黹 黽 鼎 鼓 鼠 龍',
    cue: '“河에서 물의 뜻은 氵, 소리의 힌트는 可입니다. 다른 글자도 나눠 볼까요?”',
    activity: '清·晴·請을 나란히 놓고 공통 음부 靑과 바뀌는 의미부를 색으로 표시합니다.',
    characters: [
      { glyph: '酉', reading: '닭 유', strokes: 7, kind: '상형', story: '술을 담아 발효시키는 항아리의 모습을 본뜬 글자로 설명됩니다. 부수로는 술·발효와 관련된 뜻이 많습니다.', related: ['酒 술 주', '酢 초 초', '酔 취할 취'] },
      { glyph: '靑', reading: '푸를 청', strokes: 8, kind: '의미·소리', story: '푸른빛을 나타내는 글자이면서, 형성자에서는 청에 가까운 소리를 전하는 음부로도 자주 쓰입니다.', related: ['清 맑을 청', '晴 갤 청', '請 청할 청'] },
      { glyph: '頁', reading: '머리 혈', strokes: 9, kind: '상형', story: '사람의 큰 머리와 몸을 함께 그린 모습에서 머리·얼굴과 관련된 부수가 되었습니다.', related: ['頭 머리 두', '顔 얼굴 안', '題 제목 제'] },
      { glyph: '飛', reading: '날 비', strokes: 9, kind: '상형', story: '새가 두 날개를 펼치고 공중을 나는 모습을 역동적으로 나타낸 글자입니다.', related: ['飛行 비행', '飛翔 비상', '飛躍 비약'] },
      { glyph: '鹿', reading: '사슴 록', strokes: 11, kind: '상형', story: '뿔과 긴 목, 네 다리를 지닌 사슴의 옆모습을 본뜬 글자입니다. 사슴 종류와 관련된 글자에서 보입니다.', related: ['麓 산기슭 록', '麗 고울 려', '麟 기린 린'] },
      { glyph: '魚', reading: '물고기 어', strokes: 11, kind: '상형', story: '머리·몸통·지느러미·꼬리가 보이는 물고기의 옆모습입니다. 물고기 이름과 수산 생물을 분류합니다.', related: ['鮮 고울 선', '鯨 고래 경', '漁 고기잡을 어'] },
    ],
  },
  {
    no: '10', nav: '종합 복습', title: '214부수, 하나의 지도로', focus: '찾기 · 분류 · 추론 · 설명', count: '0',
    objective: '214부수를 모두 같은 강도로 외우지 않고, 핵심 부수를 이용해 낯선 한자의 의미 영역을 추론합니다.',
    range: '핵심 60~80자는 즉시 뜻 떠올리기 · 나머지는 모양 구별과 사전 찾기 · 변형 부수는 기본형으로 되돌리기',
    cue: '“정답을 몰라도, 어떤 단서로 어디까지 추론할 수 있나요?”',
    activity: '화면의 낯선 글자를 보고 ①부수 찾기 ②의미 계열 고르기 ③추론의 근거 말하기 순서로 답합니다.',
    characters: [
      { glyph: '河', reading: '물 하', strokes: 8, kind: '추론', story: '氵가 물의 의미를 맡고 可가 소리의 단서가 됩니다. 정확한 뜻을 몰라도 ‘물과 관련된 글자’까지는 좁힐 수 있습니다.', related: ['氵 의미부', '可 음부', '海·湖 비교'] },
      { glyph: '休', reading: '쉴 휴', strokes: 6, kind: '회의', story: '사람 亻이 나무 木에 기대어 있는 모습으로 풀이합니다. 두 의미 요소의 장면을 말로 재구성해 봅니다.', related: ['亻 사람', '木 나무', '体·林 비교'] },
      { glyph: '明', reading: '밝을 명', strokes: 8, kind: '회의', story: '日과 月, 두 밝은 대상을 함께 놓아 밝음을 나타낸다고 가르치기 좋은 글자입니다.', related: ['日 해', '月 달', '照·暗 비교'] },
      { glyph: '想', reading: '생각 상', strokes: 13, kind: '형성·회의', story: '아래의 心이 생각과 마음의 의미를 받치고, 위의 相이 소리와 의미의 단서를 함께 제공합니다.', related: ['心 의미부', '相 음부', '情·忘 비교'] },
      { glyph: '清', reading: '맑을 청', strokes: 11, kind: '형성', story: '氵가 물의 의미를, 靑이 청에 가까운 소리를 제공합니다. 같은 음부를 가진 晴·請과 비교합니다.', related: ['氵 의미부', '靑 음부', '晴·請 비교'] },
    ],
  },
  {
    no: 'A', nav: '부록 · 사자소학', title: '사자소학', focus: '전문 읽기 · 원문 읽기', count: '79', appendix: true,
    objective: '사자소학 전문을 원문으로 읽고, 오늘의 언어로 뜻을 함께 살펴봅니다.',
    range: '사자소학 전문 79절',
    cue: '“이 구절의 뜻을 오늘의 관계 속에서는 어떻게 예의 있게 바꾸어 말할 수 있을까요?”',
    activity: '원문을 한 번 읽은 뒤 해석을 켜고, 지금도 지킬 수 있는 태도와 다시 생각할 점을 나누어 봅니다.',
    characters: [{ glyph: '四', reading: '넉 사', strokes: 5, kind: '부록', story: '사자소학을 위한 읽기 화면입니다.', related: [] }],
  },
];

export const timeline = [
  ['0–7', '이전 시간 복습'], ['7–30', '새 부수 탐구'], ['30–40', '실제 한자 적용'], ['40–47', '게임 · 퀴즈'], ['47–50', '핵심 5자 정리'],
];

export const standaloneExamples: Record<string, string[]> = {
  一: ['一日 일일·하루', '第一 제일·첫째'], 乙: ['甲乙 갑을', '乙種 을종'], 二: ['二月 이월', '第二 제이'],
  人: ['人口 인구', '人間 인간'], 入: ['入學 입학', '入口 입구'], 八: ['八月 팔월', '八方 팔방'], 刀: ['刀劍 도검', '短刀 단도'],
  女: ['女子 여자', '男女 남녀'], 子: ['子女 자녀', '王子 왕자'], 口: ['口語 구어', '人口 인구'], 目: ['目的 목적', '科目 과목'],
  耳: ['耳目 이목', '耳鼻科 이비과'], 手: ['手足 수족', '拍手 박수'], 足: ['足跡 족적', '不足 부족'], 心: ['心身 심신', '中心 중심'],
  首: ['首都 수도', '首席 수석'], 面: ['正面 정면', '場面 장면'], 毛: ['毛髮 모발', '羊毛 양모'], 肉: ['肉體 육체', '筋肉 근육'],
  身: ['身體 신체', '出身 출신'], 骨: ['骨格 골격', '筋骨 근골'], 牙: ['象牙 상아', '牙城 아성'], 舌: ['舌戰 설전', '毒舌 독설'],
  血: ['血液 혈액', '出血 출혈'], 爪: ['爪痕 조흔', '爪甲 조갑'], 臼: ['臼齒 구치', '石臼 석구'], 鬼: ['鬼神 귀신', '鬼門 귀문'],
  日: ['日記 일기', '每日 매일'],
  月: ['月給 월급', '歲月 세월'],
  夕: ['夕陽 석양', '秋夕 추석'],
  雨: ['雨傘 우산', '暴雨 폭우'],
  風: ['風景 풍경', '颱風 태풍'],
  山: ['登山 등산', '山脈 산맥'],
  川: ['河川 하천', '山川 산천'],
  水: ['水泳 수영', '生水 생수'],
  火: ['火山 화산', '消火 소화'],
  木: ['木手 목수', '草木 초목'],
  土: ['土地 토지', '國土 국토'],
  田: ['田畓 전답', '油田 유전'],
  石: ['石油 석유', '寶石 보석'],
  谷: ['溪谷 계곡', '峽谷 협곡'],
  穴: ['穴居 혈거', '經穴 경혈'],
  玉: ['玉座 옥좌', '白玉 백옥'],
  生: ['生命 생명', '學生 학생'],
  里: ['里長 이장', '千里 천리'],
  白: ['白色 백색', '告白 고백'],
  靑: ['靑年 청년', '靑春 청춘'],
  赤: ['赤色 적색', '赤字 적자'],
  黑: ['黑白 흑백', '暗黑 암흑'],
  黃: ['黃金 황금', '黃土 황토'],
  玄: ['玄關 현관', '玄米 현미'],
  竹: ['竹林 죽림', '爆竹 폭죽'],
  米: ['白米 백미', '玄米 현미'],
  麥: ['麥酒 맥주', '麥芽 맥아'],
  麻: ['麻藥 마약', '麻布 마포'],
  瓜: ['木瓜 모과'],
  牛: ['牛乳 우유', '韓牛 한우'],
  犬: ['愛犬 애견', '猛犬 맹견'],
  羊: ['山羊 산양', '羊毛 양모'],
  馬: ['馬車 마차', '競馬 경마'],
  鹿: ['鹿茸 녹용', '白鹿 백록'],
  虎: ['虎皮 호피', '猛虎 맹호'],
  鳥: ['鳥類 조류', '一石二鳥 일석이조'],
  羽: ['羽毛 우모'],
  魚: ['魚類 어류', '人魚 인어'],
  龍: ['龍宮 용궁', '恐龍 공룡'],
  龜: ['龜鑑 귀감', '龜裂 균열'],
  角: ['角度 각도', '頭角 두각'],
  皮: ['皮膚 피부', '脫皮 탈피'],
  戶: ['戶籍 호적', '窓戶紙 창호지'],
  門: ['大門 대문', '窓門 창문'],
  高: ['高層 고층', '最高 최고'],
  瓦: ['瓦解 와해', '靑瓦臺 청와대'],
  食: ['食事 식사', '韓食 한식'],
  甘: ['甘草 감초', '甘言利說 감언이설'],
  豆: ['豆腐 두부', '豆乳 두유'],
  酉: ['酉時 유시'],
  衣: ['衣服 의복', '脫衣 탈의'],
  巾: ['手巾 수건', '頭巾 두건'],
  革: ['革命 혁명', '改革 개혁'],
  韋: ['韋編三絶 위편삼절'],
  車: ['自動車 자동차', '人力車 인력거'],
  舟: ['一葉片舟 일엽편주'],
  金: ['金銀 금은', '貯金 저금'],
  貝: ['貝物 패물', '魚貝類 어패류'],
  弓: ['弓道 궁도', '洋弓 양궁'],
  矢: ['嚆矢 효시'],
  戈: ['干戈 간과'],
  鼓: ['鼓舞 고무', '鼓膜 고막'],
};

export const teacherNotes: Record<string, string> = {
  '01:丨': '‘뚫을 곤’이라는 훈음은 부수명입니다. 中·申 속의 세로획이 언제나 ‘뚫다’라는 뜻을 담당하는 것은 아닙니다.',
  '01:丶': '點의 뜻을 가진 이름이지만, 실제 글자에서는 작은 표시를 분류하는 역할이 큽니다. 의미부로 단정하지 않습니다.',
  '01:丿': '독립 단어로 거의 쓰지 않는 획 부수입니다. ‘삐침의 방향’을 알아보는 데 수업 목표를 둡니다.',
  '01:乙': '굽은 싹의 상형이라는 설명과 굽은 선 자체라는 설명이 함께 있습니다. 천간의 둘째 뜻은 가차된 용법입니다.',
  '01:亅': '갈고리획의 모양을 분류하는 부수입니다. 了·事의 전체 뜻을 亅 하나로 풀이하지 않습니다.',
  '01:亠': '현대에 독립 글자로 쓰기보다 윗부분을 분류하는 부수입니다. ‘돼지해머리’는 모양을 부르는 관용 명칭입니다.',
  '01:人': '왼쪽에 들어가면 亻이 되며 이름은 ‘사람인변’입니다. 入과 획이 벌어지는 방향을 비교하면 좋습니다.',
  '01:儿': '‘어진 사람 인’이라는 훈음보다 사람의 두 다리를 남긴 아랫부분이라는 자형 설명이 수업에 더 유용합니다.',
  '01:八': '본래 ‘나뉘다’의 자형으로 풀이하고, 수 8의 뜻은 빌려 쓴 것으로 설명합니다.',
  '01:冂': '뜻보다 열린 방향을 보는 형태 부수입니다. 아래가 열리며, 위가 열린 凵과 비교합니다.',
  '01:冖': '덮개 모양입니다. 宀은 점이 있는 지붕, 冖은 두 획의 덮개라는 차이를 강조합니다.',
  '01:冫': '水의 단순 변형이라기보다 얼음의 갈라진 결을 나타낸 별도 부수로 분류합니다.',
  '01:几': '현대 중국 간체 几와 모양이 같지만 여기서는 ‘안석 궤’ 부수입니다. 문맥과 자형 체계를 구별합니다.',
  '01:凵': '위가 열린 모양을 먼저 관찰합니다. 독립된 훈음 암기보다 出·函에서 테두리를 찾는 활동이 적절합니다.',
  '01:刀': '오른쪽에 서면 刂 ‘선칼도방’으로 변합니다. 자르기·나누기의 의미가 비교적 잘 남는 부수입니다.',
  '02:女': '옛 자형은 무릎을 꿇은 자세를 나타냅니다. 이를 현대 여성의 태도나 성 역할 규범으로 일반화하지 않습니다.',
  '02:子': '‘아들’뿐 아니라 아이·자식 전체를 가리키는 범위가 있습니다. 字·學에서 배움과의 연결도 보여 줍니다.',
  '02:口': '작은 口는 입, 큰 테두리 囗는 에워싼 범위를 나타냅니다. 크기와 글자 속 위치를 함께 비교합니다.',
  '02:手': '확인되는 대표 도판은 금문입니다. 부수로는 扌 ‘재방변’이 되어 손으로 하는 동작을 나타냅니다.',
  '02:足': '발만이 아니라 무릎 아래 다리까지 포함한 옛 자형으로 봅니다. 왼쪽에서는 ⻊ ‘발족변’입니다.',
  '02:心': '왼쪽 忄은 ‘심방변’, 아래 ⺗는 ‘마음심발’입니다. 月과 닮은 글자에서는 위치까지 확인합니다.',
  '02:首': '머리에서 ‘첫째·우두머리’로 뜻이 확장되었습니다. 首都는 도시의 머리라는 비유적 용법입니다.',
  '02:面': '얼굴에서 겉면·방향으로 뜻이 넓어졌습니다. 場面의 面은 구체적인 얼굴이 아닌 ‘국면’의 뜻입니다.',
  '02:肉': '부수로 들어간 月은 달 월이 아니라 ‘육달월’인 경우가 많습니다. 胃·肺·腸에서 몸의 의미를 확인합니다.',
  '02:骨': '갑골 도판은 윗부분 冎의 옛 자형으로 연결됩니다. 骨은 冎와 肉이 결합한 구조로 설명하는 편이 안전합니다.',
  '02:牙': '대표 옛 도판은 금문입니다. 芽에서는 牙가 뜻보다 소리를 돕는 부분이라는 점을 구별합니다.',
  '02:血': '그릇에 피를 담은 제의 장면이라는 풀이입니다. 오늘날의 ‘혈액’ 의미만으로 자형을 설명하면 그릇 皿이 남는 이유가 보이지 않습니다.',
  '02:爪': '위에 놓이면 爫 ‘손톱조머리’가 됩니다. 아래로 뻗은 손이라는 방향성을 采·受에서 확인합니다.',
  '02:臼': '대표 공개 도판은 소전입니다. 興·舉에서는 절구 뜻이 직접 남지 않고 구성 요소처럼 보일 수 있습니다.',
  '02:尸': '훈음이 ‘주검 시’여도 居·屋을 시체와 연결하면 안 됩니다. 굽히거나 앉은 사람의 옆모습이라는 자형을 먼저 설명합니다.',
  '02:鬼': '가면을 쓴 사람 또는 큰 머리의 존재라는 해석이 있습니다. 고대의 제의·영혼 관념과 현대의 귀신 이미지를 구분합니다.',
  '03:日': '네모난 자형은 뼈에 새기기 쉽게 둥근 해가 각져 정리된 결과입니다. 가로 왈 曰과의 폭·가운데 획 차이를 확대해 비교해 주세요.',
  '03:月': '글자 왼쪽·아래의 月 모양은 달이 아니라 육달월(肉)인 경우가 많습니다. 朝·期의 달과 育·肝의 몸을 구별해 주세요.',
  '03:夕': '갑골문에서 月과 夕은 같은 자형을 나눠 썼습니다. 多는 저녁이 쌓인 모양으로 보는 설과 고기(肉)를 포갠 모양으로 보는 설이 함께 있습니다.',
  '03:气': '한국 교육용 한자의 표준은 氣이고 气는 부수형으로만 다룹니다. 三과 닮았지만 첫 획이 삐치고 끝 획이 흘러내리는 차이를 보여 주세요.',
  '03:風': '바람 속에 왜 벌레 虫이 있는지 물어보기 좋은 글자입니다. 옛사람이 바람을 봉황·용 같은 생물과 연결해 생각했다는 설명이 일반적입니다.',
  '03:川': '부수 이름은 개미허리(巛)입니다. 順처럼 오른쪽에 온전한 川이 남는 경우와 巡처럼 巛로 꺾이는 경우를 함께 보여 주세요.',
  '03:土': '선비 사 士와 닮았습니다. 土는 아래 가로획이 더 길고 士는 위 가로획이 더 길다는 차이를 확대해 확인시켜 주세요.',
  '03:鹵': '鹵獲(노획)의 鹵는 빼앗는다는 빌려 쓴 뜻이라 본뜻(소금)과 다릅니다. 鹽(소금 염) 속에서 鹵를 찾는 활동이 알맞습니다.',
  '03:玉': '왼쪽 부수 자리에서는 점 없는 王 모양(구슬옥변)이 됩니다. 珠·理·現의 왼쪽이 임금 왕이 아니라 구슬 옥임을 강조해 주세요.',
  '03:里': '野·量·重가 里부에 속하는 것은 자형 분류의 결과이며, 뜻이 모두 마을과 이어지는 것은 아닙니다.',
  '03:白': '기원 설이 여럿이므로 한 가지로 단정하지 않습니다. 告白의 白은 아뢰다·말하다의 확장된 뜻임을 소개해 주세요.',
  '03:靑': '한국 표준 자형은 아래가 円꼴인 靑, 중국·일본은 青입니다. 획순 애니메이션은 공개 데이터(青 기준)라 아랫부분 모양이 다를 수 있습니다.',
  '03:黃': '패옥을 찬 사람 외에 불화살 모양이라는 설 등 이설이 있습니다. 橫·廣에서는 黃이 소리를 빌려주는 음부입니다.',
  '03:玄': '玄妙처럼 추상적인 뜻이 강한 글자입니다. 幺(작을 요)·糸(실 사)와 같은 실 계열 자형이라는 점만 확인해도 충분합니다.',
  '04:艸': '단독으로는 거의 쓰지 않고 위에서 艹 초두머리로 줄어듭니다. 오늘날 풀은 草로 쓰며, 艸는 부수형으로 다룹니다.',
  '04:麥': '보리 이삭을 그린 글자는 본래 來(올 래)였고, 오다라는 뜻으로 빌려 쓰이자 발을 더한 麥이 보리를 맡았다는 설명이 일반적입니다.',
  '04:黍': '오곡 가운데 기장이 낯설 수 있으니 조·수수와 같은 잡곡 사진을 함께 보여 주면 좋습니다.',
  '04:韭': '부추가 자란 모습 그대로의 그림 글자라는 점만 관찰해도 충분합니다. 억지로 외우게 하지 않습니다.',
  '04:豕': '집 家는 지붕(宀) 아래 돼지(豕)가 있는 모습입니다. 돼지를 집 안에서 기르던 옛 살림을 함께 이야기해 주세요.',
  '04:虎': '부수 표제는 머리 부분만 남긴 虍(범호엄)입니다. 處·虛에서는 호랑이의 몸이 사라지고 머리만 남는다는 점을 보여 주세요.',
  '04:豸': '훈음은 벌레 치이지만 실제로는 표범·승냥이처럼 등이 긴 맹수를 그린 부수입니다. 이름과 자형의 어긋남을 그대로 알려 주세요.',
  '04:虫': '본래 뱀을 그린 글자로 훼라고 읽습니다. 한국 한자어의 벌레 충은 蟲이 표준이고, 부수 자리에서 虫로 줄어듭니다.',
  '04:隹': '꽁지 긴 새는 鳥, 꽁지 짧은 새는 隹로 구별했다고 설명합니다. 集은 새(隹)가 나무(木) 위에 모인 모습입니다.',
  '04:黽': '개구리를 정면에서 본 모습입니다. 맹꽁이 맹 외에 힘쓸 민(黽勉)으로도 읽는 다음자입니다.',
  '04:龜': '거북 귀, 지명에 쓰는 구(龜浦), 터질 균(龜裂) 세 가지 음이 있습니다. 갑골문이 새겨진 거북 배딱지와 연결하기 좋은 글자입니다.',
  '04:角': '解는 칼(刀)로 소(牛)의 뿔(角)을 갈라내는 장면을 합친 회의자입니다. 뿔에서 모서리·각도로 뜻이 넓어졌습니다.',
  '04:皮': '손(又)으로 가죽을 벗기는 장면입니다. 왼쪽의 革(다룸가죽 혁)과 함께 가죽 계열로 묶어 다음 시간과 연결해 주세요.',
  '05:宀': '지붕 꼭대기 점이 있는 갓머리입니다. 덮개 冖(민갓머리)와 점 하나 차이라는 것을 확대해 보여 주세요.',
  '05:广': '언덕에 기대 지어 한쪽이 트인 집이라 엄호라고 부릅니다. 벼랑 厂(민엄호)과 위 점 유무로 구별합니다.',
  '05:戶': '훈음의 지게는 등짐 지게가 아니라 외짝 문을 가리키는 옛말입니다. 두 짝이면 門, 한 짝이면 戶라고 정리해 주세요.',
  '05:甘': '입 안에 단것을 머금은 모습의 지사자입니다. 맛을 나타내는 글자가 몸(舌)과 그릇(皿) 사이에 놓인다는 흐름으로 연결해 주세요.',
  '05:皿': '피 혈 血과 한 획 차이입니다. 그릇 위 한 점이 제물의 피라는 지난 시간 내용을 복습하기 좋습니다.',
  '05:豆': '본래 제사 그릇이고 콩은 빌린 뜻입니다. 豊(풍성할 풍)은 제기 위에 곡식이 가득한 모습이라는 설명과 이어집니다.',
  '05:缶': '장군은 물·술을 담는 배부른 질그릇을 가리키는 우리말입니다. 缺에서 그릇 귀퉁이가 이지러진 장면을 찾아보게 해 주세요.',
  '05:鬲': '다리 속이 비어 빨리 끓는 세발솥입니다. 발이 곧은 鼎과 나란히 놓고 비교하면 모양이 잘 보입니다.',
  '05:鼎': '나라의 권위를 상징하던 큰 솥입니다. 則·員의 옛 자형 속에 鼎이 들어 있었다는 사실은 심화 소개용입니다.',
  '05:酉': '자형은 술 항아리이고 띠 동물 닭은 빌린 용법입니다. 醫에 酉가 든 이유(소독·약술)를 물어보면 흥미로워합니다.',
  '05:糸': '단독으로 읽을 때는 가는 실 멱이고 부수 이름은 실 사입니다. 왼쪽에서 糹 실사변이 됩니다.',
  '05:网': '오늘날 그물은 網으로 씁니다. 부수 자리에서 罒로 눕는데, 買·罪의 윗부분은 눈 目이 아니라 그물이라는 점이 핵심입니다.',
  '05:革': '무두질로 가죽을 새것으로 만든다는 데서 고친다(革命·改革)는 뜻이 나왔습니다. 날가죽 皮와 구별해 주세요.',
  '05:韋': '본뜻은 성을 에워싸고 도는 발의 모습입니다. 부드러운 다룸가죽 뜻으로 쓰이며 圍·衛에 본뜻이 남아 있습니다.',
  '05:車': '수레 거와 차 두 음이 있습니다. 自動車(자동차)와 人力車(인력거)에서 음이 갈리는 것을 보여 주세요.',
  '05:金': '성씨로 읽을 때는 김입니다. 왼쪽 부수 자리에서는 釒 쇠금변이 됩니다.',
  '05:貝': '조개껍데기가 화폐였기에 재물 계열(財·買·貧)의 뜻을 맡습니다. 눈 目과의 모양 차이도 함께 확인해 주세요.',
  '05:矢': '嚆矢(효시)는 소리 나는 화살을 먼저 쏘아 전쟁의 시작을 알린 데서 온 말입니다. 처음·시초의 비유로 쓰입니다.',
  '05:戈': '我는 날이 여럿 달린 창, 成도 무기가 든 자형으로 풀이됩니다. 무기 부수가 뜻과 멀어 보이는 글자에 숨어 있음을 알려 주세요.',
  '05:殳': '오른쪽에 서서 치다·부수다의 뜻을 더하며 갖은등글월문이라 부릅니다. 攵(등글월문)과 이름이 짝을 이룹니다.',
  '05:鼓': '북틀 위의 북(壴)과 채 든 손(攴)이 합쳐졌습니다. 鼓舞는 북을 쳐 춤추게 한다, 즉 힘을 북돋운다는 뜻입니다.',
};

export const positionTypes = [
  { name: '변(邊)', place: '왼쪽', area: 'left', radicals: ['亻(休)', '氵(江)', '扌(打)', '忄(情)', '衤(初)'], description: '부수가 글자의 왼쪽에 나란히 놓입니다. 글자를 볼 때 가장 먼저 눈에 들어오는 뜻의 단서예요.' },
  { name: '방(旁)', place: '오른쪽', area: 'right', radicals: ['刂(別)', '阝(郡)', '攵(故)', '頁(順)'], description: '부수가 글자의 오른쪽에 놓입니다. 왼쪽 부분과 짝을 이루어 글자의 뜻이나 소리를 돕습니다.' },
  { name: '머리', place: '위쪽', area: 'top', radicals: ['艹(草)', '宀(安)', '⺮(答)', '雨(雪)'], description: '부수가 글자의 맨 위에 올라갑니다. 지붕이나 풀처럼 위에서 덮는 모양을 떠올리면 쉬워요.' },
  { name: '발', place: '아래쪽', area: 'bottom', radicals: ['灬(熱)', '⺗(恭)', '皿(益)', '儿(元)'], description: '부수가 글자의 아래를 받칩니다. 글자의 발처럼 가장 아랫자리에 놓이는 부수예요.' },
  { name: '엄', place: '위·왼쪽', area: 'cover', radicals: ['广(床)', '厂(厚)', '尸(居)', '疒(病)'], description: '부수가 글자의 위와 왼쪽을 덮듯 놓입니다. 안쪽의 다른 부분을 감싸는 모양을 확인해 보세요.' },
  { name: '몸', place: '바깥', area: 'surround', radicals: ['門(問)', '囗(國)', '凵(函)'], description: '부수가 글자의 바깥을 둘러쌉니다. 안에 다른 부분을 품는 틀처럼 보이는 자리예요.' },
  { name: '받침', place: '왼쪽 아래', area: 'base', radicals: ['辶(近)', '廴(建)', '走(趙)'], description: '부수가 글자의 왼쪽 아래에서 나머지 부분을 받칩니다. 길이나 움직임을 나타내는 글자에서 자주 만나요.' },
  { name: '제부수', place: '글자 전체', area: 'whole', radicals: ['木(木)', '日(日)', '山(山)'], description: '글자 전체가 그대로 부수입니다. 다른 부분과 결합하지 않아도 하나의 부수로 쓰여요.' },
];

export const strokeRules = [
  ['1', '위에서 아래로', '三 · 言'], ['2', '왼쪽에서 오른쪽으로', '川 · 林'], ['3', '가로획 뒤에 세로획', '十 · 王'], ['4', '삐침 뒤에 파임', '人 · 文'],
  ['5', '바깥을 먼저, 안을 나중', '同 · 月'], ['6', '둘러싼 글자는 마지막에 닫기', '國 · 回'], ['7', '가운데 뒤에 양옆', '小 · 水'], ['8', '꿰뚫는 획·받침은 뒤에', '中 · 道'],
];

export const evolutionSteps = [
  { name: '갑골문', period: '상 후기', image: '/oracle/人.svg', note: '뼈에 새겨 직선적' },
  { name: '금문', period: '상·주', image: '/oracle/evolution-person-bronze.png', note: '청동기에 주조' },
  { name: '소전', period: '진', image: '/oracle/evolution-person-seal.png', note: '곡선을 고르게 통일' },
  { name: '예서', period: '진·한', image: '/oracle/evolution-person-clerical.png', note: '붓쓰기용으로 납작해짐' },
  { name: '해서', period: '후한 이후', glyph: '人', note: '획이 정돈되어 표준화' },
];

export const introSlides = [
  { label: 'OPENING', title: '한자는 왜 배울까?', description: '수업을 시작하기 전, 오늘의 배움이 나와 어떻게 이어지는지 생각해 봅니다.' },
  { label: 'RADICAL POSITION', title: '부수는 글자 안에서 자리를 잡아요', description: '같은 한자 구성 요소도 놓인 자리에 따라 읽는 이름이 달라집니다.' },
  { label: 'RADICAL VARIANTS', title: '자리가 바뀌면 모양도 달라져요', description: '글자 안에 자연스럽게 들어가기 위해 부수는 조금씩 모습을 바꿉니다.' },
  { label: 'STROKE ORDER', title: '필순에는 읽기 쉬운 흐름이 있어요', description: '글자를 쓰는 순서도 모양을 안정적으로 기억하게 하는 규칙입니다.' },
  { label: 'SCRIPT EVOLUTION', title: '그림은 오랜 시간 글자가 되었어요', description: '사람의 모습을 그린 人이 오늘의 한자로 정리되기까지를 살펴봅니다.' },
];
